// Code generated by scripts/generate.py. DO NOT EDIT.

package diesis

import "github.com/ethereum/go-ethereum/common"

// System contract and precompile addresses from canonical.json.
var (
	// DiesisStaking is DIESIS_STAKING.
	DiesisStaking = common.HexToAddress("0xd1e5150000000000000000000000000000000001")
	// DiesisPatron is DIESIS_PATRON.
	DiesisPatron = common.HexToAddress("0xd1e5150000000000000000000000000000000002")
	// DiesisConfig is DIESIS_CONFIG.
	DiesisConfig = common.HexToAddress("0xd1e5150000000000000000000000000000000003")
	// BootstrapOracle is BOOTSTRAP_ORACLE.
	BootstrapOracle = common.HexToAddress("0xd1e5150000000000000000000000000000000004")
	// BootstrapConfig is BOOTSTRAP_CONFIG.
	BootstrapConfig = common.HexToAddress("0xd1e5150000000000000000000000000000000005")
	// DiesisStateWriter is DIESIS_STATE_WRITER.
	DiesisStateWriter = common.HexToAddress("0xd1e5150000000000000000000000000000000010")
	// DiesisPosition is DIESIS_POSITION.
	DiesisPosition = common.HexToAddress("0xd1e5150000000000000000000000000000000020")
	// DiesisBundleEscrow is DIESIS_BUNDLE_ESCROW.
	DiesisBundleEscrow = common.HexToAddress("0xd1e515000000000000000000000000000000be5c")
	// WrappedDS is WRAPPED_DS.
	WrappedDS = common.HexToAddress("0xd1e51500000000000000000000000000000000d5")
	// LiquidStakedDS is LIQUID_STAKED_DS.
	LiquidStakedDS = common.HexToAddress("0xd1e51500000000000000000000000000000ac1d5")
	// DiesisTestUSD is DIESIS_TEST_USD.
	DiesisTestUSD = common.HexToAddress("0xd1e5150000000000000000000000000000000040")
	// DiesisMarkets is DIESIS_MARKETS.
	DiesisMarkets = common.HexToAddress("0xd1e515000000000000000000000000000000b00c")
	// DiesisSpotBook is DIESIS_SPOT_BOOK.
	DiesisSpotBook = common.HexToAddress("0xd1e515000000000000000000000000000000590d")
	// DiesisPerpsBook is DIESIS_PERPS_BOOK.
	DiesisPerpsBook = common.HexToAddress("0xd1e5150000000000000000000000000000009e29")
	// DiesisMargin is DIESIS_MARGIN.
	DiesisMargin = common.HexToAddress("0xd1e515000000000000000000000000000000a1ce")
	// DiesisSettlement is DIESIS_SETTLEMENT.
	DiesisSettlement = common.HexToAddress("0xd1e5150000000000000000000000000000005e71")
	// DiesisSettlementRouter is DIESIS_SETTLEMENT_ROUTER.
	DiesisSettlementRouter = common.HexToAddress("0xd1e5150000000000000000000000000000005e72")
	// DiesisConductors is DIESIS_CONDUCTORS.
	DiesisConductors = common.HexToAddress("0x00d1e5150000000000000000000000000000c0de")
	// DiesisCoreVault is DIESIS_CORE_VAULT.
	DiesisCoreVault = common.HexToAddress("0x00d1e5150000000000000000000000000000c04e")
	// DiesisIssuanceAuction is DIESIS_ISSUANCE_AUCTION.
	DiesisIssuanceAuction = common.HexToAddress("0x00d1e5150000000000000000000000000000a0c7")
	// DiesisBuybackBurn is DIESIS_BUYBACK_BURN.
	DiesisBuybackBurn = common.HexToAddress("0x0d1e51500000000000000000000000000000bb07")
	// DiesisOperatorBond is DIESIS_OPERATOR_BOND.
	DiesisOperatorBond = common.HexToAddress("0x00d1e5150000000000000000000000000000bacd")
	// DiesisERC20Factory is DIESIS_ERC20_FACTORY.
	DiesisERC20Factory = common.HexToAddress("0x00d1e5150000000000000000000000000000f00c")
	// DiesisPerpDeploy is DIESIS_PERP_DEPLOY.
	DiesisPerpDeploy = common.HexToAddress("0x00d1e5150000000000000000000000000000defb")
	// DiesisNameRegistry is DIESIS_NAME_REGISTRY.
	DiesisNameRegistry = common.HexToAddress("0xd1e5150000000000000000000000000000000050")
	// DiesisBaseRegistrar is DIESIS_BASE_REGISTRAR.
	DiesisBaseRegistrar = common.HexToAddress("0xd1e5150000000000000000000000000000000051")
	// DiesisPublicResolver is DIESIS_PUBLIC_RESOLVER.
	DiesisPublicResolver = common.HexToAddress("0xd1e5150000000000000000000000000000000052")
	// DiesisReverseRegistrar is DIESIS_REVERSE_REGISTRAR.
	DiesisReverseRegistrar = common.HexToAddress("0xd1e5150000000000000000000000000000000053")
	// DiesisNameVerifier is DIESIS_NAME_VERIFIER.
	DiesisNameVerifier = common.HexToAddress("0xd1e5150000000000000000000000000000000054")
	// DiesisNamePolicy is DIESIS_NAME_POLICY.
	DiesisNamePolicy = common.HexToAddress("0xd1e5150000000000000000000000000000000055")
	// VRF is VRF.
	VRF = common.HexToAddress("0xd1e5150000000000000000000000000000005eed")
	// StealthRegistry is STEALTH_REGISTRY.
	StealthRegistry = common.HexToAddress("0xd1e5150000000000000000000000000000facade")
	// StealthAnnouncer is STEALTH_ANNOUNCER.
	StealthAnnouncer = common.HexToAddress("0xd1e515000000000000000000000000000000ca5e")
	// ShieldedPool is SHIELDED_POOL.
	ShieldedPool = common.HexToAddress("0xd1e515000000000000000000000000000000fade")
	// PrivacyPools is PRIVACY_POOLS.
	PrivacyPools = common.HexToAddress("0xd1e5150000000000000000000000000000deface")
	// Groth16Verifier is GROTH16_VERIFIER.
	Groth16Verifier = common.HexToAddress("0xd1e515000000000000000000000000000000deed")
	// Secp256r1 is SECP256R1.
	Secp256r1 = common.HexToAddress("0x0000000000000000000000000000000000000100")
	// Poseidon is POSEIDON.
	Poseidon = common.HexToAddress("0x0000000000000000000000000000000000000200")
	// MLDSA is ML_DSA.
	MLDSA = common.HexToAddress("0x0000000000000000000000000000000000000300")
	// Multicall3 is MULTICALL3.
	Multicall3 = common.HexToAddress("0xca11bde05977b3631167028862be2a173976ca11")
	// Permit2 is PERMIT2.
	Permit2 = common.HexToAddress("0x000000000022d473030f116ddee9f6b43ac78ba3")
)

// Addresses maps each canonical.json address name, such as
// "DIESIS_STAKING", to its address.
var Addresses = map[string]common.Address{
	"DIESIS_STAKING":           DiesisStaking,
	"DIESIS_PATRON":            DiesisPatron,
	"DIESIS_CONFIG":            DiesisConfig,
	"BOOTSTRAP_ORACLE":         BootstrapOracle,
	"BOOTSTRAP_CONFIG":         BootstrapConfig,
	"DIESIS_STATE_WRITER":      DiesisStateWriter,
	"DIESIS_POSITION":          DiesisPosition,
	"DIESIS_BUNDLE_ESCROW":     DiesisBundleEscrow,
	"WRAPPED_DS":               WrappedDS,
	"LIQUID_STAKED_DS":         LiquidStakedDS,
	"DIESIS_TEST_USD":          DiesisTestUSD,
	"DIESIS_MARKETS":           DiesisMarkets,
	"DIESIS_SPOT_BOOK":         DiesisSpotBook,
	"DIESIS_PERPS_BOOK":        DiesisPerpsBook,
	"DIESIS_MARGIN":            DiesisMargin,
	"DIESIS_SETTLEMENT":        DiesisSettlement,
	"DIESIS_SETTLEMENT_ROUTER": DiesisSettlementRouter,
	"DIESIS_CONDUCTORS":        DiesisConductors,
	"DIESIS_CORE_VAULT":        DiesisCoreVault,
	"DIESIS_ISSUANCE_AUCTION":  DiesisIssuanceAuction,
	"DIESIS_BUYBACK_BURN":      DiesisBuybackBurn,
	"DIESIS_OPERATOR_BOND":     DiesisOperatorBond,
	"DIESIS_ERC20_FACTORY":     DiesisERC20Factory,
	"DIESIS_PERP_DEPLOY":       DiesisPerpDeploy,
	"DIESIS_NAME_REGISTRY":     DiesisNameRegistry,
	"DIESIS_BASE_REGISTRAR":    DiesisBaseRegistrar,
	"DIESIS_PUBLIC_RESOLVER":   DiesisPublicResolver,
	"DIESIS_REVERSE_REGISTRAR": DiesisReverseRegistrar,
	"DIESIS_NAME_VERIFIER":     DiesisNameVerifier,
	"DIESIS_NAME_POLICY":       DiesisNamePolicy,
	"VRF":                      VRF,
	"STEALTH_REGISTRY":         StealthRegistry,
	"STEALTH_ANNOUNCER":        StealthAnnouncer,
	"SHIELDED_POOL":            ShieldedPool,
	"PRIVACY_POOLS":            PrivacyPools,
	"GROTH16_VERIFIER":         Groth16Verifier,
	"SECP256R1":                Secp256r1,
	"POSEIDON":                 Poseidon,
	"ML_DSA":                   MLDSA,
	"MULTICALL3":               Multicall3,
	"PERMIT2":                  Permit2,
}
