// Code generated by scripts/generate.py. DO NOT EDIT.

package diesis

import "github.com/0xDiesis/diesis-go/contracts"

// ContractTable has one entry per public system contract with a fixed
// address. Field names match the keys of diesisContracts in the
// TypeScript SDK.
type ContractTable struct {
	Markets          Contract // IDiesisMarkets
	SpotBook         Contract // IDiesisSpotBook
	PerpsBook        Contract // IDiesisPerpsBook
	Margin           Contract // IDiesisMargin
	Settlement       Contract // IDiesisSettlement
	SettlementRouter Contract // DiesisSettlementRouter
	Conductors       Contract // IDiesisConductors
	ERC20Factory     Contract // IDiesisErc20Factory
	PerpDeploy       Contract // IDiesisPerpDeploy
	OperatorBond     Contract // IDiesisOperatorBond
	BundleEscrow     Contract // IDiesisBundleEscrow
	Staking          Contract // DiesisStaking
	Position         Contract // IDiesisPosition
	LiquidStakedDS   Contract // ILiquidStakedDS
	WrappedDS        Contract // IWrappedDS
	Patron           Contract // DiesisPatron
	Config           Contract // DiesisConfig
	CoreVault        Contract // IDiesisCoreVault
	IssuanceAuction  Contract // IDiesisIssuanceAuction
	BuybackBurn      Contract // IDiesisBuybackBurn
	ShieldedPool     Contract // DiesisShieldedPool
	PrivacyPools     Contract // DiesisPrivacyPools
	NameRegistry     Contract // IDiesisNameRegistry
	BaseRegistrar    Contract // DiesisBaseRegistrar
	PublicResolver   Contract // DiesisPublicResolver
	ReverseRegistrar Contract // IDiesisReverseRegistrar
	NameVerifier     Contract // IDiesisNameVerifier
	NamePolicy       Contract // IDiesisNamePolicy
}

// Contracts pairs each fixed-address public system contract with its
// address and generated ABI.
var Contracts = ContractTable{
	Markets:          Contract{Key: "markets", Name: "IDiesisMarkets", Address: DiesisMarkets, ABI: contracts.IDiesisMarketsABI},
	SpotBook:         Contract{Key: "spotBook", Name: "IDiesisSpotBook", Address: DiesisSpotBook, ABI: contracts.IDiesisSpotBookABI},
	PerpsBook:        Contract{Key: "perpsBook", Name: "IDiesisPerpsBook", Address: DiesisPerpsBook, ABI: contracts.IDiesisPerpsBookABI},
	Margin:           Contract{Key: "margin", Name: "IDiesisMargin", Address: DiesisMargin, ABI: contracts.IDiesisMarginABI},
	Settlement:       Contract{Key: "settlement", Name: "IDiesisSettlement", Address: DiesisSettlement, ABI: contracts.IDiesisSettlementABI},
	SettlementRouter: Contract{Key: "settlementRouter", Name: "DiesisSettlementRouter", Address: DiesisSettlementRouter, ABI: contracts.DiesisSettlementRouterABI},
	Conductors:       Contract{Key: "conductors", Name: "IDiesisConductors", Address: DiesisConductors, ABI: contracts.IDiesisConductorsABI},
	ERC20Factory:     Contract{Key: "erc20Factory", Name: "IDiesisErc20Factory", Address: DiesisERC20Factory, ABI: contracts.IDiesisErc20FactoryABI},
	PerpDeploy:       Contract{Key: "perpDeploy", Name: "IDiesisPerpDeploy", Address: DiesisPerpDeploy, ABI: contracts.IDiesisPerpDeployABI},
	OperatorBond:     Contract{Key: "operatorBond", Name: "IDiesisOperatorBond", Address: DiesisOperatorBond, ABI: contracts.IDiesisOperatorBondABI},
	BundleEscrow:     Contract{Key: "bundleEscrow", Name: "IDiesisBundleEscrow", Address: DiesisBundleEscrow, ABI: contracts.IDiesisBundleEscrowABI},
	Staking:          Contract{Key: "staking", Name: "DiesisStaking", Address: DiesisStaking, ABI: contracts.DiesisStakingABI},
	Position:         Contract{Key: "position", Name: "IDiesisPosition", Address: DiesisPosition, ABI: contracts.IDiesisPositionABI},
	LiquidStakedDS:   Contract{Key: "liquidStakedDS", Name: "ILiquidStakedDS", Address: LiquidStakedDS, ABI: contracts.ILiquidStakedDSABI},
	WrappedDS:        Contract{Key: "wrappedDS", Name: "IWrappedDS", Address: WrappedDS, ABI: contracts.IWrappedDSABI},
	Patron:           Contract{Key: "patron", Name: "DiesisPatron", Address: DiesisPatron, ABI: contracts.DiesisPatronABI},
	Config:           Contract{Key: "config", Name: "DiesisConfig", Address: DiesisConfig, ABI: contracts.DiesisConfigABI},
	CoreVault:        Contract{Key: "coreVault", Name: "IDiesisCoreVault", Address: DiesisCoreVault, ABI: contracts.IDiesisCoreVaultABI},
	IssuanceAuction:  Contract{Key: "issuanceAuction", Name: "IDiesisIssuanceAuction", Address: DiesisIssuanceAuction, ABI: contracts.IDiesisIssuanceAuctionABI},
	BuybackBurn:      Contract{Key: "buybackBurn", Name: "IDiesisBuybackBurn", Address: DiesisBuybackBurn, ABI: contracts.IDiesisBuybackBurnABI},
	ShieldedPool:     Contract{Key: "shieldedPool", Name: "DiesisShieldedPool", Address: ShieldedPool, ABI: contracts.DiesisShieldedPoolABI},
	PrivacyPools:     Contract{Key: "privacyPools", Name: "DiesisPrivacyPools", Address: PrivacyPools, ABI: contracts.DiesisPrivacyPoolsABI},
	NameRegistry:     Contract{Key: "nameRegistry", Name: "IDiesisNameRegistry", Address: DiesisNameRegistry, ABI: contracts.IDiesisNameRegistryABI},
	BaseRegistrar:    Contract{Key: "baseRegistrar", Name: "DiesisBaseRegistrar", Address: DiesisBaseRegistrar, ABI: contracts.DiesisBaseRegistrarABI},
	PublicResolver:   Contract{Key: "publicResolver", Name: "DiesisPublicResolver", Address: DiesisPublicResolver, ABI: contracts.DiesisPublicResolverABI},
	ReverseRegistrar: Contract{Key: "reverseRegistrar", Name: "IDiesisReverseRegistrar", Address: DiesisReverseRegistrar, ABI: contracts.IDiesisReverseRegistrarABI},
	NameVerifier:     Contract{Key: "nameVerifier", Name: "IDiesisNameVerifier", Address: DiesisNameVerifier, ABI: contracts.IDiesisNameVerifierABI},
	NamePolicy:       Contract{Key: "namePolicy", Name: "IDiesisNamePolicy", Address: DiesisNamePolicy, ABI: contracts.IDiesisNamePolicyABI},
}

// All returns every entry in the table, in the TypeScript SDK's order.
func (t ContractTable) All() []Contract {
	return []Contract{
		t.Markets,
		t.SpotBook,
		t.PerpsBook,
		t.Margin,
		t.Settlement,
		t.SettlementRouter,
		t.Conductors,
		t.ERC20Factory,
		t.PerpDeploy,
		t.OperatorBond,
		t.BundleEscrow,
		t.Staking,
		t.Position,
		t.LiquidStakedDS,
		t.WrappedDS,
		t.Patron,
		t.Config,
		t.CoreVault,
		t.IssuanceAuction,
		t.BuybackBurn,
		t.ShieldedPool,
		t.PrivacyPools,
		t.NameRegistry,
		t.BaseRegistrar,
		t.PublicResolver,
		t.ReverseRegistrar,
		t.NameVerifier,
		t.NamePolicy,
	}
}

// ABIs maps every public contract name, including contracts without a
// fixed address, to its generated ABI JSON.
var ABIs = map[string]string{
	"IDiesisMarkets":          contracts.IDiesisMarketsABI,
	"IDiesisSpotBook":         contracts.IDiesisSpotBookABI,
	"IDiesisPerpsBook":        contracts.IDiesisPerpsBookABI,
	"IDiesisMargin":           contracts.IDiesisMarginABI,
	"IDiesisSettlement":       contracts.IDiesisSettlementABI,
	"DiesisSettlementRouter":  contracts.DiesisSettlementRouterABI,
	"IDiesisConductors":       contracts.IDiesisConductorsABI,
	"IDiesisErc20Factory":     contracts.IDiesisErc20FactoryABI,
	"IDiesisPerpDeploy":       contracts.IDiesisPerpDeployABI,
	"IDiesisOperatorBond":     contracts.IDiesisOperatorBondABI,
	"IDiesisBundleEscrow":     contracts.IDiesisBundleEscrowABI,
	"DiesisStaking":           contracts.DiesisStakingABI,
	"IDiesisPosition":         contracts.IDiesisPositionABI,
	"IValidatorShare":         contracts.IValidatorShareABI,
	"ILiquidStakedDS":         contracts.ILiquidStakedDSABI,
	"IWrappedDS":              contracts.IWrappedDSABI,
	"DiesisPatron":            contracts.DiesisPatronABI,
	"DiesisConfig":            contracts.DiesisConfigABI,
	"IDiesisCoreVault":        contracts.IDiesisCoreVaultABI,
	"IDiesisIssuanceAuction":  contracts.IDiesisIssuanceAuctionABI,
	"IDiesisBuybackBurn":      contracts.IDiesisBuybackBurnABI,
	"DiesisShieldedPool":      contracts.DiesisShieldedPoolABI,
	"DiesisPrivacyPools":      contracts.DiesisPrivacyPoolsABI,
	"IDiesisNameRegistry":     contracts.IDiesisNameRegistryABI,
	"DiesisBaseRegistrar":     contracts.DiesisBaseRegistrarABI,
	"DiesisPublicResolver":    contracts.DiesisPublicResolverABI,
	"IDiesisReverseRegistrar": contracts.IDiesisReverseRegistrarABI,
	"IDiesisNameVerifier":     contracts.IDiesisNameVerifierABI,
	"IDiesisNamePolicy":       contracts.IDiesisNamePolicyABI,
}
