// Code generated by abi-typegen. DO NOT EDIT.

package contracts

import (
	"bytes"
	"context"
	"fmt"
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// IDiesisReverseRegistrarABI is the JSON ABI of the IDiesisReverseRegistrar contract.
const IDiesisReverseRegistrarABI = `[{"inputs":[{"internalType":"address","name":"controller","type":"address"}],"name":"controllers","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"addr","type":"address"}],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"addr","type":"address"}],"name":"node","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"pure","type":"function"},{"inputs":[{"internalType":"address","name":"controller","type":"address"},{"internalType":"bool","name":"approved","type":"bool"}],"name":"setController","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"name_","type":"string"}],"name":"setName","outputs":[{"internalType":"bytes32","name":"node","type":"bytes32"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"addr","type":"address"},{"internalType":"string","name":"name_","type":"string"}],"name":"setNameForAddr","outputs":[{"internalType":"bytes32","name":"node","type":"bytes32"}],"stateMutability":"nonpayable","type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"controller","type":"address"},{"indexed":false,"internalType":"bool","name":"approved","type":"bool"}],"name":"ControllerChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"addr","type":"address"},{"indexed":false,"internalType":"string","name":"name","type":"string"}],"name":"ReverseNameChanged","type":"event"},{"inputs":[],"name":"InvalidName","type":"error"},{"inputs":[],"name":"NotAuthorized","type":"error"}]`

// Canonical signatures of the IDiesisReverseRegistrar contract's functions, events, and errors.
const (
	IDiesisReverseRegistrarControllersSignature             = "controllers(address)"
	IDiesisReverseRegistrarNameSignature                    = "name(address)"
	IDiesisReverseRegistrarNodeSignature                    = "node(address)"
	IDiesisReverseRegistrarSetControllerSignature           = "setController(address,bool)"
	IDiesisReverseRegistrarSetNameSignature                 = "setName(string)"
	IDiesisReverseRegistrarSetNameForAddrSignature          = "setNameForAddr(address,string)"
	IDiesisReverseRegistrarControllerChangedEventSignature  = "ControllerChanged(address,bool)"
	IDiesisReverseRegistrarReverseNameChangedEventSignature = "ReverseNameChanged(address,string)"
	IDiesisReverseRegistrarInvalidNameErrorSignature        = "InvalidName()"
	IDiesisReverseRegistrarNotAuthorizedErrorSignature      = "NotAuthorized()"
)

// Selectors and event topics of the IDiesisReverseRegistrar contract.
var (
	IDiesisReverseRegistrarControllersSelector          = [4]byte{0xda, 0x8c, 0x22, 0x9e}
	IDiesisReverseRegistrarNameSelector                 = [4]byte{0x01, 0x98, 0x48, 0x92}
	IDiesisReverseRegistrarNodeSelector                 = [4]byte{0xbf, 0xfb, 0xe6, 0x1c}
	IDiesisReverseRegistrarSetControllerSelector        = [4]byte{0xe0, 0xdb, 0xa6, 0x0f}
	IDiesisReverseRegistrarSetNameSelector              = [4]byte{0xc4, 0x7f, 0x00, 0x27}
	IDiesisReverseRegistrarSetNameForAddrSelector       = [4]byte{0xc9, 0x11, 0x99, 0x41}
	IDiesisReverseRegistrarControllerChangedEventTopic  = common.HexToHash("0x4c97694570a07277810af7e5669ffd5f6a2d6b74b6e9a274b8b870fd5114cf87")
	IDiesisReverseRegistrarReverseNameChangedEventTopic = common.HexToHash("0x874858272df7029774df09958c496ec3708deb07a0d89c349dfb96f153b42490")
	IDiesisReverseRegistrarInvalidNameErrorSelector     = [4]byte{0x43, 0x0f, 0x13, 0xb3}
	IDiesisReverseRegistrarNotAuthorizedErrorSelector   = [4]byte{0xea, 0x8e, 0x4e, 0xb5}
)

// IDiesisReverseRegistrarControllersParams holds the arguments of controllers(address).
type IDiesisReverseRegistrarControllersParams struct {
	Controller common.Address
}

// IDiesisReverseRegistrarNameParams holds the arguments of name(address).
type IDiesisReverseRegistrarNameParams struct {
	Addr common.Address
}

// IDiesisReverseRegistrarNodeParams holds the arguments of node(address).
type IDiesisReverseRegistrarNodeParams struct {
	Addr common.Address
}

// IDiesisReverseRegistrarSetControllerParams holds the arguments of setController(address,bool).
type IDiesisReverseRegistrarSetControllerParams struct {
	Controller common.Address
	Approved   bool
}

// IDiesisReverseRegistrarSetNameParams holds the arguments of setName(string).
type IDiesisReverseRegistrarSetNameParams struct {
	Name string
}

// IDiesisReverseRegistrarSetNameForAddrParams holds the arguments of setNameForAddr(address,string).
type IDiesisReverseRegistrarSetNameForAddrParams struct {
	Addr common.Address
	Name string
}

// IDiesisReverseRegistrarControllerChangedEvent holds the fields of the ControllerChanged(address,bool) event.
type IDiesisReverseRegistrarControllerChangedEvent struct {
	Controller common.Address
	Approved   bool
}

// IDiesisReverseRegistrarReverseNameChangedEvent holds the fields of the ReverseNameChanged(address,string) event.
type IDiesisReverseRegistrarReverseNameChangedEvent struct {
	Addr common.Address
	Name string
}

// IDiesisReverseRegistrarInvalidNameError holds the arguments of the InvalidName() error.
type IDiesisReverseRegistrarInvalidNameError struct{}

// IDiesisReverseRegistrarNotAuthorizedError holds the arguments of the NotAuthorized() error.
type IDiesisReverseRegistrarNotAuthorizedError struct{}

// IDiesisReverseRegistrarBinding provides typed calls, transactions, logs, and offline ABI encoding.
type IDiesisReverseRegistrarBinding struct {
	abi     abi.ABI
	bound   *bind.BoundContract
	backend bind.ContractBackend
	address common.Address
}

// NewIDiesisReverseRegistrarBinding parses the ABI and binds an optional backend. Pass nil for offline encoding and decoding.
func NewIDiesisReverseRegistrarBinding(address common.Address, backend bind.ContractBackend) (*IDiesisReverseRegistrarBinding, error) {
	parsed, err := abi.JSON(strings.NewReader(IDiesisReverseRegistrarABI))
	if err != nil {
		return nil, err
	}
	var bound *bind.BoundContract
	if backend != nil {
		bound = bind.NewBoundContract(address, parsed, backend, backend, backend)
	}
	return &IDiesisReverseRegistrarBinding{abi: parsed, bound: bound, backend: backend, address: address}, nil
}

// ABI returns the parsed contract ABI.
func (c *IDiesisReverseRegistrarBinding) ABI() abi.ABI { return c.abi }

func (c *IDiesisReverseRegistrarBinding) method(signature string) (abi.Method, error) {
	for _, method := range c.abi.Methods {
		if method.Sig == signature {
			return method, nil
		}
	}
	return abi.Method{}, fmt.Errorf("unknown method %s", signature)
}

func (c *IDiesisReverseRegistrarBinding) event(signature string) (abi.Event, error) {
	for _, event := range c.abi.Events {
		if event.Sig == signature {
			return event, nil
		}
	}
	return abi.Event{}, fmt.Errorf("unknown event %s", signature)
}

func (c *IDiesisReverseRegistrarBinding) customError(signature string) (abi.Error, error) {
	for _, definition := range c.abi.Errors {
		if definition.Sig == signature {
			return definition, nil
		}
	}
	return abi.Error{}, fmt.Errorf("unknown error %s", signature)
}

// EncodeConstructor encodes the constructor arguments without bytecode.
func (c *IDiesisReverseRegistrarBinding) EncodeConstructor() ([]byte, error) {
	return c.abi.Pack("")
}

// DeployIDiesisReverseRegistrarBinding deploys caller-supplied bytecode with typed constructor arguments.
func DeployIDiesisReverseRegistrarBinding(opts *bind.TransactOpts, backend bind.ContractBackend, bytecode []byte) (common.Address, *types.Transaction, *IDiesisReverseRegistrarBinding, error) {
	if opts == nil || backend == nil {
		return common.Address{}, nil, nil, fmt.Errorf("transaction options and backend are required")
	}
	if len(bytecode) == 0 {
		return common.Address{}, nil, nil, fmt.Errorf("deployment bytecode is empty")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return common.Address{}, nil, nil, fmt.Errorf("constructor is not payable")
	}
	parsed, err := abi.JSON(strings.NewReader(IDiesisReverseRegistrarABI))
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	address, tx, _, err := bind.DeployContract(opts, parsed, bytecode, backend)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	binding, err := NewIDiesisReverseRegistrarBinding(address, backend)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	return address, tx, binding, nil
}

// EncodeControllers encodes calldata for "controllers(address)".
func (c *IDiesisReverseRegistrarBinding) EncodeControllers(params IDiesisReverseRegistrarControllersParams) ([]byte, error) {
	method, err := c.method("controllers(address)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.Controller)
}

// IDiesisReverseRegistrarControllersResult holds the outputs of "controllers(address)".
type IDiesisReverseRegistrarControllersResult struct {
	Bool bool
}

// DecodeControllersResult decodes the return data of "controllers(address)".
func (c *IDiesisReverseRegistrarBinding) DecodeControllersResult(data []byte) (out IDiesisReverseRegistrarControllersResult, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI result: %v", failure)
		}
	}()
	method, err := c.method("controllers(address)")
	if err != nil {
		return out, err
	}
	values, err := method.Outputs.Unpack(data)
	if err != nil {
		return out, err
	}
	if len(values) != 1 {
		return out, fmt.Errorf("result value count mismatch")
	}
	out.Bool = *abi.ConvertType(values[0], new(bool)).(*bool)
	return out, nil
}

// Controllers calls "controllers(address)" on the bound backend.
func (c *IDiesisReverseRegistrarBinding) Controllers(opts *bind.CallOpts, params IDiesisReverseRegistrarControllersParams) (IDiesisReverseRegistrarControllersResult, error) {
	var zero IDiesisReverseRegistrarControllersResult
	if c.bound == nil {
		return zero, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	input, err := c.EncodeControllers(params)
	if err != nil {
		return zero, err
	}
	output, err := c.bound.CallRaw(opts, input)
	if err != nil {
		return zero, err
	}
	return c.DecodeControllersResult(output)
}

// EncodeName encodes calldata for "name(address)".
func (c *IDiesisReverseRegistrarBinding) EncodeName(params IDiesisReverseRegistrarNameParams) ([]byte, error) {
	method, err := c.method("name(address)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.Addr)
}

// IDiesisReverseRegistrarNameResult holds the outputs of "name(address)".
type IDiesisReverseRegistrarNameResult struct {
	String string
}

// DecodeNameResult decodes the return data of "name(address)".
func (c *IDiesisReverseRegistrarBinding) DecodeNameResult(data []byte) (out IDiesisReverseRegistrarNameResult, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI result: %v", failure)
		}
	}()
	method, err := c.method("name(address)")
	if err != nil {
		return out, err
	}
	values, err := method.Outputs.Unpack(data)
	if err != nil {
		return out, err
	}
	if len(values) != 1 {
		return out, fmt.Errorf("result value count mismatch")
	}
	out.String = *abi.ConvertType(values[0], new(string)).(*string)
	return out, nil
}

// Name calls "name(address)" on the bound backend.
func (c *IDiesisReverseRegistrarBinding) Name(opts *bind.CallOpts, params IDiesisReverseRegistrarNameParams) (IDiesisReverseRegistrarNameResult, error) {
	var zero IDiesisReverseRegistrarNameResult
	if c.bound == nil {
		return zero, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	input, err := c.EncodeName(params)
	if err != nil {
		return zero, err
	}
	output, err := c.bound.CallRaw(opts, input)
	if err != nil {
		return zero, err
	}
	return c.DecodeNameResult(output)
}

// EncodeNode encodes calldata for "node(address)".
func (c *IDiesisReverseRegistrarBinding) EncodeNode(params IDiesisReverseRegistrarNodeParams) ([]byte, error) {
	method, err := c.method("node(address)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.Addr)
}

// IDiesisReverseRegistrarNodeResult holds the outputs of "node(address)".
type IDiesisReverseRegistrarNodeResult struct {
	Bytes32 [32]byte
}

// DecodeNodeResult decodes the return data of "node(address)".
func (c *IDiesisReverseRegistrarBinding) DecodeNodeResult(data []byte) (out IDiesisReverseRegistrarNodeResult, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI result: %v", failure)
		}
	}()
	method, err := c.method("node(address)")
	if err != nil {
		return out, err
	}
	values, err := method.Outputs.Unpack(data)
	if err != nil {
		return out, err
	}
	if len(values) != 1 {
		return out, fmt.Errorf("result value count mismatch")
	}
	out.Bytes32 = *abi.ConvertType(values[0], new([32]byte)).(*[32]byte)
	return out, nil
}

// Node calls "node(address)" on the bound backend.
func (c *IDiesisReverseRegistrarBinding) Node(opts *bind.CallOpts, params IDiesisReverseRegistrarNodeParams) (IDiesisReverseRegistrarNodeResult, error) {
	var zero IDiesisReverseRegistrarNodeResult
	if c.bound == nil {
		return zero, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	input, err := c.EncodeNode(params)
	if err != nil {
		return zero, err
	}
	output, err := c.bound.CallRaw(opts, input)
	if err != nil {
		return zero, err
	}
	return c.DecodeNodeResult(output)
}

// EncodeSetController encodes calldata for "setController(address,bool)".
func (c *IDiesisReverseRegistrarBinding) EncodeSetController(params IDiesisReverseRegistrarSetControllerParams) ([]byte, error) {
	method, err := c.method("setController(address,bool)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.Controller, params.Approved)
}

// DecodeSetControllerResult validates the empty return data of "setController(address,bool)".
func (c *IDiesisReverseRegistrarBinding) DecodeSetControllerResult(data []byte) error {
	if len(data) != 0 {
		return fmt.Errorf("unexpected return data for %s", "setController(address,bool)")
	}
	return nil
}

// SetController submits "setController(address,bool)"; opts supplies signer, gas, and optional value.
func (c *IDiesisReverseRegistrarBinding) SetController(opts *bind.TransactOpts, params IDiesisReverseRegistrarSetControllerParams) (*types.Transaction, error) {
	if c.bound == nil {
		return nil, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	if opts == nil {
		return nil, fmt.Errorf("transaction options are required")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return nil, fmt.Errorf("%s is not payable", "setController(address,bool)")
	}
	method, err := c.method("setController(address,bool)")
	if err != nil {
		return nil, err
	}
	return c.bound.Transact(opts, method.Name, params.Controller, params.Approved)
}

// EncodeSetName encodes calldata for "setName(string)".
func (c *IDiesisReverseRegistrarBinding) EncodeSetName(params IDiesisReverseRegistrarSetNameParams) ([]byte, error) {
	method, err := c.method("setName(string)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.Name)
}

// IDiesisReverseRegistrarSetNameResult holds the outputs of "setName(string)".
type IDiesisReverseRegistrarSetNameResult struct {
	Node [32]byte
}

// DecodeSetNameResult decodes the return data of "setName(string)".
func (c *IDiesisReverseRegistrarBinding) DecodeSetNameResult(data []byte) (out IDiesisReverseRegistrarSetNameResult, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI result: %v", failure)
		}
	}()
	method, err := c.method("setName(string)")
	if err != nil {
		return out, err
	}
	values, err := method.Outputs.Unpack(data)
	if err != nil {
		return out, err
	}
	if len(values) != 1 {
		return out, fmt.Errorf("result value count mismatch")
	}
	out.Node = *abi.ConvertType(values[0], new([32]byte)).(*[32]byte)
	return out, nil
}

// SetName submits "setName(string)"; opts supplies signer, gas, and optional value.
func (c *IDiesisReverseRegistrarBinding) SetName(opts *bind.TransactOpts, params IDiesisReverseRegistrarSetNameParams) (*types.Transaction, error) {
	if c.bound == nil {
		return nil, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	if opts == nil {
		return nil, fmt.Errorf("transaction options are required")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return nil, fmt.Errorf("%s is not payable", "setName(string)")
	}
	method, err := c.method("setName(string)")
	if err != nil {
		return nil, err
	}
	return c.bound.Transact(opts, method.Name, params.Name)
}

// EncodeSetNameForAddr encodes calldata for "setNameForAddr(address,string)".
func (c *IDiesisReverseRegistrarBinding) EncodeSetNameForAddr(params IDiesisReverseRegistrarSetNameForAddrParams) ([]byte, error) {
	method, err := c.method("setNameForAddr(address,string)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.Addr, params.Name)
}

// IDiesisReverseRegistrarSetNameForAddrResult holds the outputs of "setNameForAddr(address,string)".
type IDiesisReverseRegistrarSetNameForAddrResult struct {
	Node [32]byte
}

// DecodeSetNameForAddrResult decodes the return data of "setNameForAddr(address,string)".
func (c *IDiesisReverseRegistrarBinding) DecodeSetNameForAddrResult(data []byte) (out IDiesisReverseRegistrarSetNameForAddrResult, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI result: %v", failure)
		}
	}()
	method, err := c.method("setNameForAddr(address,string)")
	if err != nil {
		return out, err
	}
	values, err := method.Outputs.Unpack(data)
	if err != nil {
		return out, err
	}
	if len(values) != 1 {
		return out, fmt.Errorf("result value count mismatch")
	}
	out.Node = *abi.ConvertType(values[0], new([32]byte)).(*[32]byte)
	return out, nil
}

// SetNameForAddr submits "setNameForAddr(address,string)"; opts supplies signer, gas, and optional value.
func (c *IDiesisReverseRegistrarBinding) SetNameForAddr(opts *bind.TransactOpts, params IDiesisReverseRegistrarSetNameForAddrParams) (*types.Transaction, error) {
	if c.bound == nil {
		return nil, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	if opts == nil {
		return nil, fmt.Errorf("transaction options are required")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return nil, fmt.Errorf("%s is not payable", "setNameForAddr(address,string)")
	}
	method, err := c.method("setNameForAddr(address,string)")
	if err != nil {
		return nil, err
	}
	return c.bound.Transact(opts, method.Name, params.Addr, params.Name)
}

// DecodeControllerChangedEvent decodes a "ControllerChanged(address,bool)" log.
func (c *IDiesisReverseRegistrarBinding) DecodeControllerChangedEvent(log types.Log) (out IDiesisReverseRegistrarControllerChangedEvent, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI event: %v", failure)
		}
	}()
	definition, err := c.event("ControllerChanged(address,bool)")
	if err != nil {
		return out, err
	}
	if len(log.Topics) == 0 || log.Topics[0] != definition.ID {
		return out, fmt.Errorf("event signature mismatch for %s", "ControllerChanged(address,bool)")
	}
	if len(log.Topics) != 2 {
		return out, fmt.Errorf("event topic count mismatch for %s", "ControllerChanged(address,bool)")
	}
	if len(definition.Inputs.NonIndexed()) > 0 {
		values, err := definition.Inputs.NonIndexed().Unpack(log.Data)
		if err != nil {
			return out, err
		}
		if len(values) != 1 {
			return out, fmt.Errorf("event value count mismatch")
		}
		out.Approved = *abi.ConvertType(values[0], new(bool)).(*bool)
	} else if len(log.Data) != 0 {
		return out, fmt.Errorf("unexpected event data")
	}
	var indexed abi.Arguments
	var indexedTopics []common.Hash
	indexed = append(indexed, definition.Inputs[0])
	indexedTopics = append(indexedTopics, log.Topics[1])
	if err := abi.ParseTopics(&out, indexed, indexedTopics); err != nil {
		return out, err
	}
	return out, nil
}

// FilterControllerChanged retrieves and decodes "ControllerChanged(address,bool)" logs. Indexed filters follow ABI order.
func (c *IDiesisReverseRegistrarBinding) FilterControllerChanged(ctx context.Context, from, to *big.Int, indexed ...[]any) ([]IDiesisReverseRegistrarControllerChangedEvent, error) {
	if c.backend == nil {
		return nil, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	definition, err := c.event("ControllerChanged(address,bool)")
	if err != nil {
		return nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, fmt.Errorf("too many indexed filters for %s", "ControllerChanged(address,bool)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, err
	}
	logs, err := c.backend.FilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics, FromBlock: from, ToBlock: to})
	if err != nil {
		return nil, err
	}
	out := make([]IDiesisReverseRegistrarControllerChangedEvent, 0, len(logs))
	for _, log := range logs {
		decoded, err := c.DecodeControllerChangedEvent(log)
		if err != nil {
			return nil, err
		}
		out = append(out, decoded)
	}
	return out, nil
}

// WatchControllerChanged subscribes to new "ControllerChanged(address,bool)" logs and decodes them. Call Unsubscribe on the returned subscription when done.
func (c *IDiesisReverseRegistrarBinding) WatchControllerChanged(ctx context.Context, indexed ...[]any) (<-chan IDiesisReverseRegistrarControllerChangedEvent, event.Subscription, error) {
	if c.backend == nil {
		return nil, nil, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	definition, err := c.event("ControllerChanged(address,bool)")
	if err != nil {
		return nil, nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, nil, fmt.Errorf("too many indexed filters for %s", "ControllerChanged(address,bool)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, nil, err
	}
	logs := make(chan types.Log)
	upstream, err := c.backend.SubscribeFilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics}, logs)
	if err != nil {
		return nil, nil, err
	}
	events := make(chan IDiesisReverseRegistrarControllerChangedEvent)
	subscription := event.NewSubscription(func(quit <-chan struct{}) error {
		defer upstream.Unsubscribe()
		defer close(events)
		for {
			select {
			case <-quit:
				return nil
			case <-ctx.Done():
				return ctx.Err()
			case err, ok := <-upstream.Err():
				if !ok {
					return nil
				}
				return err
			case log, ok := <-logs:
				if !ok {
					return nil
				}
				decoded, err := c.DecodeControllerChangedEvent(log)
				if err != nil {
					return err
				}
				select {
				case events <- decoded:
				case <-quit:
					return nil
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})
	return events, subscription, nil
}

// DecodeReverseNameChangedEvent decodes a "ReverseNameChanged(address,string)" log.
func (c *IDiesisReverseRegistrarBinding) DecodeReverseNameChangedEvent(log types.Log) (out IDiesisReverseRegistrarReverseNameChangedEvent, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI event: %v", failure)
		}
	}()
	definition, err := c.event("ReverseNameChanged(address,string)")
	if err != nil {
		return out, err
	}
	if len(log.Topics) == 0 || log.Topics[0] != definition.ID {
		return out, fmt.Errorf("event signature mismatch for %s", "ReverseNameChanged(address,string)")
	}
	if len(log.Topics) != 2 {
		return out, fmt.Errorf("event topic count mismatch for %s", "ReverseNameChanged(address,string)")
	}
	if len(definition.Inputs.NonIndexed()) > 0 {
		values, err := definition.Inputs.NonIndexed().Unpack(log.Data)
		if err != nil {
			return out, err
		}
		if len(values) != 1 {
			return out, fmt.Errorf("event value count mismatch")
		}
		out.Name = *abi.ConvertType(values[0], new(string)).(*string)
	} else if len(log.Data) != 0 {
		return out, fmt.Errorf("unexpected event data")
	}
	var indexed abi.Arguments
	var indexedTopics []common.Hash
	indexed = append(indexed, definition.Inputs[0])
	indexedTopics = append(indexedTopics, log.Topics[1])
	if err := abi.ParseTopics(&out, indexed, indexedTopics); err != nil {
		return out, err
	}
	return out, nil
}

// FilterReverseNameChanged retrieves and decodes "ReverseNameChanged(address,string)" logs. Indexed filters follow ABI order.
func (c *IDiesisReverseRegistrarBinding) FilterReverseNameChanged(ctx context.Context, from, to *big.Int, indexed ...[]any) ([]IDiesisReverseRegistrarReverseNameChangedEvent, error) {
	if c.backend == nil {
		return nil, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	definition, err := c.event("ReverseNameChanged(address,string)")
	if err != nil {
		return nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, fmt.Errorf("too many indexed filters for %s", "ReverseNameChanged(address,string)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, err
	}
	logs, err := c.backend.FilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics, FromBlock: from, ToBlock: to})
	if err != nil {
		return nil, err
	}
	out := make([]IDiesisReverseRegistrarReverseNameChangedEvent, 0, len(logs))
	for _, log := range logs {
		decoded, err := c.DecodeReverseNameChangedEvent(log)
		if err != nil {
			return nil, err
		}
		out = append(out, decoded)
	}
	return out, nil
}

// WatchReverseNameChanged subscribes to new "ReverseNameChanged(address,string)" logs and decodes them. Call Unsubscribe on the returned subscription when done.
func (c *IDiesisReverseRegistrarBinding) WatchReverseNameChanged(ctx context.Context, indexed ...[]any) (<-chan IDiesisReverseRegistrarReverseNameChangedEvent, event.Subscription, error) {
	if c.backend == nil {
		return nil, nil, fmt.Errorf("IDiesisReverseRegistrarBinding has no backend")
	}
	definition, err := c.event("ReverseNameChanged(address,string)")
	if err != nil {
		return nil, nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, nil, fmt.Errorf("too many indexed filters for %s", "ReverseNameChanged(address,string)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, nil, err
	}
	logs := make(chan types.Log)
	upstream, err := c.backend.SubscribeFilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics}, logs)
	if err != nil {
		return nil, nil, err
	}
	events := make(chan IDiesisReverseRegistrarReverseNameChangedEvent)
	subscription := event.NewSubscription(func(quit <-chan struct{}) error {
		defer upstream.Unsubscribe()
		defer close(events)
		for {
			select {
			case <-quit:
				return nil
			case <-ctx.Done():
				return ctx.Err()
			case err, ok := <-upstream.Err():
				if !ok {
					return nil
				}
				return err
			case log, ok := <-logs:
				if !ok {
					return nil
				}
				decoded, err := c.DecodeReverseNameChangedEvent(log)
				if err != nil {
					return err
				}
				select {
				case events <- decoded:
				case <-quit:
					return nil
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})
	return events, subscription, nil
}

// DecodeInvalidNameError decodes a "InvalidName()" revert payload, including its selector.
func (c *IDiesisReverseRegistrarBinding) DecodeInvalidNameError(raw []byte) (out IDiesisReverseRegistrarInvalidNameError, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI error: %v", failure)
		}
	}()
	definition, err := c.customError("InvalidName()")
	if err != nil {
		return out, err
	}
	if len(raw) < 4 || !bytes.Equal(raw[:4], definition.ID[:4]) {
		return out, fmt.Errorf("error selector mismatch for %s", "InvalidName()")
	}
	values, err := definition.Inputs.Unpack(raw[4:])
	if err != nil {
		return out, err
	}
	if len(values) != 0 {
		return out, fmt.Errorf("error value count mismatch")
	}
	return out, nil
}

// DecodeNotAuthorizedError decodes a "NotAuthorized()" revert payload, including its selector.
func (c *IDiesisReverseRegistrarBinding) DecodeNotAuthorizedError(raw []byte) (out IDiesisReverseRegistrarNotAuthorizedError, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI error: %v", failure)
		}
	}()
	definition, err := c.customError("NotAuthorized()")
	if err != nil {
		return out, err
	}
	if len(raw) < 4 || !bytes.Equal(raw[:4], definition.ID[:4]) {
		return out, fmt.Errorf("error selector mismatch for %s", "NotAuthorized()")
	}
	values, err := definition.Inputs.Unpack(raw[4:])
	if err != nil {
		return out, err
	}
	if len(values) != 0 {
		return out, fmt.Errorf("error value count mismatch")
	}
	return out, nil
}

// DecodeError identifies and decodes a declared custom error.
func (c *IDiesisReverseRegistrarBinding) DecodeError(raw []byte) (any, error) {
	if len(raw) < 4 {
		return nil, fmt.Errorf("revert payload is shorter than a selector")
	}
	if definition, err := c.customError("InvalidName()"); err == nil && bytes.Equal(raw[:4], definition.ID[:4]) {
		return c.DecodeInvalidNameError(raw)
	}
	if definition, err := c.customError("NotAuthorized()"); err == nil && bytes.Equal(raw[:4], definition.ID[:4]) {
		return c.DecodeNotAuthorizedError(raw)
	}
	return nil, fmt.Errorf("unknown custom error selector %x", raw[:4])
}
