// Code generated by abi-typegen. DO NOT EDIT.

package contracts

import (
	"context"
	"fmt"
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// IDiesisMarginABI is the JSON ABI of the IDiesisMargin contract.
const IDiesisMarginABI = `[{"inputs":[{"internalType":"bytes32","name":"marketId","type":"bytes32"}],"name":"resolvePerpProtection","outputs":[{"internalType":"bytes32","name":"transactionId","type":"bytes32"}],"stateMutability":"nonpayable","type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"marketId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"deleveraged","type":"address"},{"indexed":true,"internalType":"address","name":"counterparty","type":"address"},{"indexed":false,"internalType":"uint256","name":"size","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"price","type":"uint256"}],"name":"AutoDeleverage","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"marketId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"trader","type":"address"},{"indexed":false,"internalType":"uint256","name":"size","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"price","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"penalty","type":"uint256"}],"name":"Liquidation","type":"event"}]`

// Canonical signatures of the IDiesisMargin contract's functions, events, and errors.
const (
	IDiesisMarginResolvePerpProtectionSignature = "resolvePerpProtection(bytes32)"
	IDiesisMarginAutoDeleverageEventSignature   = "AutoDeleverage(bytes32,address,address,uint256,uint256)"
	IDiesisMarginLiquidationEventSignature      = "Liquidation(bytes32,address,uint256,uint256,uint256)"
)

// Selectors and event topics of the IDiesisMargin contract.
var (
	IDiesisMarginResolvePerpProtectionSelector = [4]byte{0x94, 0x48, 0x12, 0x98}
	IDiesisMarginAutoDeleverageEventTopic      = common.HexToHash("0xa313ba5ab2a04b36e5925a4d9166509adc0e0b74f2fb3080801b862d143a0cb6")
	IDiesisMarginLiquidationEventTopic         = common.HexToHash("0x3ba36e5650f62551141712b1c51bb87efe733d5e06ba74059260acc44e998448")
)

// IDiesisMarginResolvePerpProtectionParams holds the arguments of resolvePerpProtection(bytes32).
//
// System-owned canonical frontier resolution. External callers are rejected.
type IDiesisMarginResolvePerpProtectionParams struct {
	MarketId [32]byte
}

// IDiesisMarginAutoDeleverageEvent holds the fields of the AutoDeleverage(bytes32,address,address,uint256,uint256) event.
type IDiesisMarginAutoDeleverageEvent struct {
	MarketId     [32]byte
	Deleveraged  common.Address
	Counterparty common.Address
	Size         *big.Int
	Price        *big.Int
}

// IDiesisMarginLiquidationEvent holds the fields of the Liquidation(bytes32,address,uint256,uint256,uint256) event.
type IDiesisMarginLiquidationEvent struct {
	MarketId [32]byte
	Trader   common.Address
	Size     *big.Int
	Price    *big.Int
	Penalty  *big.Int
}

// IDiesisMarginBinding provides typed calls, transactions, logs, and offline ABI encoding.
type IDiesisMarginBinding struct {
	abi     abi.ABI
	bound   *bind.BoundContract
	backend bind.ContractBackend
	address common.Address
}

// NewIDiesisMarginBinding parses the ABI and binds an optional backend. Pass nil for offline encoding and decoding.
func NewIDiesisMarginBinding(address common.Address, backend bind.ContractBackend) (*IDiesisMarginBinding, error) {
	parsed, err := abi.JSON(strings.NewReader(IDiesisMarginABI))
	if err != nil {
		return nil, err
	}
	var bound *bind.BoundContract
	if backend != nil {
		bound = bind.NewBoundContract(address, parsed, backend, backend, backend)
	}
	return &IDiesisMarginBinding{abi: parsed, bound: bound, backend: backend, address: address}, nil
}

// ABI returns the parsed contract ABI.
func (c *IDiesisMarginBinding) ABI() abi.ABI { return c.abi }

func (c *IDiesisMarginBinding) method(signature string) (abi.Method, error) {
	for _, method := range c.abi.Methods {
		if method.Sig == signature {
			return method, nil
		}
	}
	return abi.Method{}, fmt.Errorf("unknown method %s", signature)
}

func (c *IDiesisMarginBinding) event(signature string) (abi.Event, error) {
	for _, event := range c.abi.Events {
		if event.Sig == signature {
			return event, nil
		}
	}
	return abi.Event{}, fmt.Errorf("unknown event %s", signature)
}

func (c *IDiesisMarginBinding) customError(signature string) (abi.Error, error) {
	for _, definition := range c.abi.Errors {
		if definition.Sig == signature {
			return definition, nil
		}
	}
	return abi.Error{}, fmt.Errorf("unknown error %s", signature)
}

// EncodeConstructor encodes the constructor arguments without bytecode.
func (c *IDiesisMarginBinding) EncodeConstructor() ([]byte, error) {
	return c.abi.Pack("")
}

// DeployIDiesisMarginBinding deploys caller-supplied bytecode with typed constructor arguments.
func DeployIDiesisMarginBinding(opts *bind.TransactOpts, backend bind.ContractBackend, bytecode []byte) (common.Address, *types.Transaction, *IDiesisMarginBinding, error) {
	if opts == nil || backend == nil {
		return common.Address{}, nil, nil, fmt.Errorf("transaction options and backend are required")
	}
	if len(bytecode) == 0 {
		return common.Address{}, nil, nil, fmt.Errorf("deployment bytecode is empty")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return common.Address{}, nil, nil, fmt.Errorf("constructor is not payable")
	}
	parsed, err := abi.JSON(strings.NewReader(IDiesisMarginABI))
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	address, tx, _, err := bind.DeployContract(opts, parsed, bytecode, backend)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	binding, err := NewIDiesisMarginBinding(address, backend)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	return address, tx, binding, nil
}

// EncodeResolvePerpProtection encodes calldata for "resolvePerpProtection(bytes32)".
func (c *IDiesisMarginBinding) EncodeResolvePerpProtection(params IDiesisMarginResolvePerpProtectionParams) ([]byte, error) {
	method, err := c.method("resolvePerpProtection(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.MarketId)
}

// IDiesisMarginResolvePerpProtectionResult holds the outputs of "resolvePerpProtection(bytes32)".
type IDiesisMarginResolvePerpProtectionResult struct {
	TransactionId [32]byte
}

// DecodeResolvePerpProtectionResult decodes the return data of "resolvePerpProtection(bytes32)".
func (c *IDiesisMarginBinding) DecodeResolvePerpProtectionResult(data []byte) (out IDiesisMarginResolvePerpProtectionResult, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI result: %v", failure)
		}
	}()
	method, err := c.method("resolvePerpProtection(bytes32)")
	if err != nil {
		return out, err
	}
	values, err := method.Outputs.Unpack(data)
	if err != nil {
		return out, err
	}
	if len(values) != 1 {
		return out, fmt.Errorf("result value count mismatch")
	}
	out.TransactionId = *abi.ConvertType(values[0], new([32]byte)).(*[32]byte)
	return out, nil
}

// ResolvePerpProtection submits "resolvePerpProtection(bytes32)"; opts supplies signer, gas, and optional value.
func (c *IDiesisMarginBinding) ResolvePerpProtection(opts *bind.TransactOpts, params IDiesisMarginResolvePerpProtectionParams) (*types.Transaction, error) {
	if c.bound == nil {
		return nil, fmt.Errorf("IDiesisMarginBinding has no backend")
	}
	if opts == nil {
		return nil, fmt.Errorf("transaction options are required")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return nil, fmt.Errorf("%s is not payable", "resolvePerpProtection(bytes32)")
	}
	method, err := c.method("resolvePerpProtection(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.bound.Transact(opts, method.Name, params.MarketId)
}

// DecodeAutoDeleverageEvent decodes a "AutoDeleverage(bytes32,address,address,uint256,uint256)" log.
func (c *IDiesisMarginBinding) DecodeAutoDeleverageEvent(log types.Log) (out IDiesisMarginAutoDeleverageEvent, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI event: %v", failure)
		}
	}()
	definition, err := c.event("AutoDeleverage(bytes32,address,address,uint256,uint256)")
	if err != nil {
		return out, err
	}
	if len(log.Topics) == 0 || log.Topics[0] != definition.ID {
		return out, fmt.Errorf("event signature mismatch for %s", "AutoDeleverage(bytes32,address,address,uint256,uint256)")
	}
	if len(log.Topics) != 4 {
		return out, fmt.Errorf("event topic count mismatch for %s", "AutoDeleverage(bytes32,address,address,uint256,uint256)")
	}
	if len(definition.Inputs.NonIndexed()) > 0 {
		values, err := definition.Inputs.NonIndexed().Unpack(log.Data)
		if err != nil {
			return out, err
		}
		if len(values) != 2 {
			return out, fmt.Errorf("event value count mismatch")
		}
		out.Size = *abi.ConvertType(values[0], new(*big.Int)).(**big.Int)
		out.Price = *abi.ConvertType(values[1], new(*big.Int)).(**big.Int)
	} else if len(log.Data) != 0 {
		return out, fmt.Errorf("unexpected event data")
	}
	var indexed abi.Arguments
	var indexedTopics []common.Hash
	indexed = append(indexed, definition.Inputs[0])
	indexedTopics = append(indexedTopics, log.Topics[1])
	indexed = append(indexed, definition.Inputs[1])
	indexedTopics = append(indexedTopics, log.Topics[2])
	indexed = append(indexed, definition.Inputs[2])
	indexedTopics = append(indexedTopics, log.Topics[3])
	if err := abi.ParseTopics(&out, indexed, indexedTopics); err != nil {
		return out, err
	}
	return out, nil
}

// FilterAutoDeleverage retrieves and decodes "AutoDeleverage(bytes32,address,address,uint256,uint256)" logs. Indexed filters follow ABI order.
func (c *IDiesisMarginBinding) FilterAutoDeleverage(ctx context.Context, from, to *big.Int, indexed ...[]any) ([]IDiesisMarginAutoDeleverageEvent, error) {
	if c.backend == nil {
		return nil, fmt.Errorf("IDiesisMarginBinding has no backend")
	}
	definition, err := c.event("AutoDeleverage(bytes32,address,address,uint256,uint256)")
	if err != nil {
		return nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, fmt.Errorf("too many indexed filters for %s", "AutoDeleverage(bytes32,address,address,uint256,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, err
	}
	logs, err := c.backend.FilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics, FromBlock: from, ToBlock: to})
	if err != nil {
		return nil, err
	}
	out := make([]IDiesisMarginAutoDeleverageEvent, 0, len(logs))
	for _, log := range logs {
		decoded, err := c.DecodeAutoDeleverageEvent(log)
		if err != nil {
			return nil, err
		}
		out = append(out, decoded)
	}
	return out, nil
}

// WatchAutoDeleverage subscribes to new "AutoDeleverage(bytes32,address,address,uint256,uint256)" logs and decodes them. Call Unsubscribe on the returned subscription when done.
func (c *IDiesisMarginBinding) WatchAutoDeleverage(ctx context.Context, indexed ...[]any) (<-chan IDiesisMarginAutoDeleverageEvent, event.Subscription, error) {
	if c.backend == nil {
		return nil, nil, fmt.Errorf("IDiesisMarginBinding has no backend")
	}
	definition, err := c.event("AutoDeleverage(bytes32,address,address,uint256,uint256)")
	if err != nil {
		return nil, nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, nil, fmt.Errorf("too many indexed filters for %s", "AutoDeleverage(bytes32,address,address,uint256,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, nil, err
	}
	logs := make(chan types.Log)
	upstream, err := c.backend.SubscribeFilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics}, logs)
	if err != nil {
		return nil, nil, err
	}
	events := make(chan IDiesisMarginAutoDeleverageEvent)
	subscription := event.NewSubscription(func(quit <-chan struct{}) error {
		defer upstream.Unsubscribe()
		defer close(events)
		for {
			select {
			case <-quit:
				return nil
			case <-ctx.Done():
				return ctx.Err()
			case err, ok := <-upstream.Err():
				if !ok {
					return nil
				}
				return err
			case log, ok := <-logs:
				if !ok {
					return nil
				}
				decoded, err := c.DecodeAutoDeleverageEvent(log)
				if err != nil {
					return err
				}
				select {
				case events <- decoded:
				case <-quit:
					return nil
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})
	return events, subscription, nil
}

// DecodeLiquidationEvent decodes a "Liquidation(bytes32,address,uint256,uint256,uint256)" log.
func (c *IDiesisMarginBinding) DecodeLiquidationEvent(log types.Log) (out IDiesisMarginLiquidationEvent, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI event: %v", failure)
		}
	}()
	definition, err := c.event("Liquidation(bytes32,address,uint256,uint256,uint256)")
	if err != nil {
		return out, err
	}
	if len(log.Topics) == 0 || log.Topics[0] != definition.ID {
		return out, fmt.Errorf("event signature mismatch for %s", "Liquidation(bytes32,address,uint256,uint256,uint256)")
	}
	if len(log.Topics) != 3 {
		return out, fmt.Errorf("event topic count mismatch for %s", "Liquidation(bytes32,address,uint256,uint256,uint256)")
	}
	if len(definition.Inputs.NonIndexed()) > 0 {
		values, err := definition.Inputs.NonIndexed().Unpack(log.Data)
		if err != nil {
			return out, err
		}
		if len(values) != 3 {
			return out, fmt.Errorf("event value count mismatch")
		}
		out.Size = *abi.ConvertType(values[0], new(*big.Int)).(**big.Int)
		out.Price = *abi.ConvertType(values[1], new(*big.Int)).(**big.Int)
		out.Penalty = *abi.ConvertType(values[2], new(*big.Int)).(**big.Int)
	} else if len(log.Data) != 0 {
		return out, fmt.Errorf("unexpected event data")
	}
	var indexed abi.Arguments
	var indexedTopics []common.Hash
	indexed = append(indexed, definition.Inputs[0])
	indexedTopics = append(indexedTopics, log.Topics[1])
	indexed = append(indexed, definition.Inputs[1])
	indexedTopics = append(indexedTopics, log.Topics[2])
	if err := abi.ParseTopics(&out, indexed, indexedTopics); err != nil {
		return out, err
	}
	return out, nil
}

// FilterLiquidation retrieves and decodes "Liquidation(bytes32,address,uint256,uint256,uint256)" logs. Indexed filters follow ABI order.
func (c *IDiesisMarginBinding) FilterLiquidation(ctx context.Context, from, to *big.Int, indexed ...[]any) ([]IDiesisMarginLiquidationEvent, error) {
	if c.backend == nil {
		return nil, fmt.Errorf("IDiesisMarginBinding has no backend")
	}
	definition, err := c.event("Liquidation(bytes32,address,uint256,uint256,uint256)")
	if err != nil {
		return nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, fmt.Errorf("too many indexed filters for %s", "Liquidation(bytes32,address,uint256,uint256,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, err
	}
	logs, err := c.backend.FilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics, FromBlock: from, ToBlock: to})
	if err != nil {
		return nil, err
	}
	out := make([]IDiesisMarginLiquidationEvent, 0, len(logs))
	for _, log := range logs {
		decoded, err := c.DecodeLiquidationEvent(log)
		if err != nil {
			return nil, err
		}
		out = append(out, decoded)
	}
	return out, nil
}

// WatchLiquidation subscribes to new "Liquidation(bytes32,address,uint256,uint256,uint256)" logs and decodes them. Call Unsubscribe on the returned subscription when done.
func (c *IDiesisMarginBinding) WatchLiquidation(ctx context.Context, indexed ...[]any) (<-chan IDiesisMarginLiquidationEvent, event.Subscription, error) {
	if c.backend == nil {
		return nil, nil, fmt.Errorf("IDiesisMarginBinding has no backend")
	}
	definition, err := c.event("Liquidation(bytes32,address,uint256,uint256,uint256)")
	if err != nil {
		return nil, nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, nil, fmt.Errorf("too many indexed filters for %s", "Liquidation(bytes32,address,uint256,uint256,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, nil, err
	}
	logs := make(chan types.Log)
	upstream, err := c.backend.SubscribeFilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics}, logs)
	if err != nil {
		return nil, nil, err
	}
	events := make(chan IDiesisMarginLiquidationEvent)
	subscription := event.NewSubscription(func(quit <-chan struct{}) error {
		defer upstream.Unsubscribe()
		defer close(events)
		for {
			select {
			case <-quit:
				return nil
			case <-ctx.Done():
				return ctx.Err()
			case err, ok := <-upstream.Err():
				if !ok {
					return nil
				}
				return err
			case log, ok := <-logs:
				if !ok {
					return nil
				}
				decoded, err := c.DecodeLiquidationEvent(log)
				if err != nil {
					return err
				}
				select {
				case events <- decoded:
				case <-quit:
					return nil
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})
	return events, subscription, nil
}

// DecodeError identifies and decodes a declared custom error.
func (c *IDiesisMarginBinding) DecodeError(raw []byte) (any, error) {
	if len(raw) < 4 {
		return nil, fmt.Errorf("revert payload is shorter than a selector")
	}
	return nil, fmt.Errorf("unknown custom error selector %x", raw[:4])
}
