// Code generated by abi-typegen. DO NOT EDIT.

package contracts

import (
	"context"
	"fmt"
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// IDiesisOperatorBondABI is the JSON ABI of the IDiesisOperatorBond contract.
const IDiesisOperatorBondABI = `[{"inputs":[{"internalType":"bytes32","name":"marketId","type":"bytes32"}],"name":"finalizeRelease","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"marketId","type":"bytes32"}],"name":"getBond","outputs":[{"components":[{"internalType":"address","name":"operator","type":"address"},{"internalType":"bytes32","name":"marketId","type":"bytes32"},{"internalType":"uint256","name":"bondDs","type":"uint256"},{"internalType":"uint64","name":"releaseUnlockBlock","type":"uint64"}],"internalType":"struct IDiesisOperatorBond.BondInfo","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"marketId","type":"bytes32"}],"name":"postBond","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"marketId","type":"bytes32"}],"name":"requestRelease","outputs":[],"stateMutability":"nonpayable","type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"operator","type":"address"},{"indexed":true,"internalType":"bytes32","name":"marketId","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"bondDs","type":"uint256"}],"name":"BondPosted","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"marketId","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"amountDs","type":"uint256"}],"name":"BondSlashed","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"marketId","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"refundedDs","type":"uint256"}],"name":"ReleaseFinalized","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"marketId","type":"bytes32"},{"indexed":false,"internalType":"uint64","name":"unlockBlock","type":"uint64"}],"name":"ReleaseRequested","type":"event"}]`

// Canonical signatures of the IDiesisOperatorBond contract's functions, events, and errors.
const (
	IDiesisOperatorBondFinalizeReleaseSignature       = "finalizeRelease(bytes32)"
	IDiesisOperatorBondGetBondSignature               = "getBond(bytes32)"
	IDiesisOperatorBondPostBondSignature              = "postBond(bytes32)"
	IDiesisOperatorBondRequestReleaseSignature        = "requestRelease(bytes32)"
	IDiesisOperatorBondBondPostedEventSignature       = "BondPosted(address,bytes32,uint256)"
	IDiesisOperatorBondBondSlashedEventSignature      = "BondSlashed(bytes32,uint256)"
	IDiesisOperatorBondReleaseFinalizedEventSignature = "ReleaseFinalized(bytes32,uint256)"
	IDiesisOperatorBondReleaseRequestedEventSignature = "ReleaseRequested(bytes32,uint64)"
)

// Selectors and event topics of the IDiesisOperatorBond contract.
var (
	IDiesisOperatorBondFinalizeReleaseSelector    = [4]byte{0x7c, 0x66, 0xce, 0xa2}
	IDiesisOperatorBondGetBondSelector            = [4]byte{0x26, 0xd6, 0xc9, 0x7b}
	IDiesisOperatorBondPostBondSelector           = [4]byte{0xfa, 0x66, 0x29, 0xf9}
	IDiesisOperatorBondRequestReleaseSelector     = [4]byte{0x00, 0x5d, 0xd2, 0x04}
	IDiesisOperatorBondBondPostedEventTopic       = common.HexToHash("0xcf22bbd4a2fe722ca22351cce65e409b7feadd7e8495d2a9212c8b44b4e8ea24")
	IDiesisOperatorBondBondSlashedEventTopic      = common.HexToHash("0xaf9f84551ac4989ebd3133324f530341c312ed19efaa94e9f7d18d69ca4522c5")
	IDiesisOperatorBondReleaseFinalizedEventTopic = common.HexToHash("0xf510fb6525b869fd60bff6b95c29aac36e6177a38e5491bac3dadf962ae6436e")
	IDiesisOperatorBondReleaseRequestedEventTopic = common.HexToHash("0x1e2897f0a7b147eee142499ca46524d060a653dfc994c60a8b9e67ef9ab8c47a")
)

// IDiesisOperatorBondBondInfo is the Go form of the BondInfo tuple.
type IDiesisOperatorBondBondInfo struct {
	Operator           common.Address
	MarketId           [32]byte
	BondDs             *big.Int
	ReleaseUnlockBlock uint64
}

// IDiesisOperatorBondFinalizeReleaseParams holds the arguments of finalizeRelease(bytes32).
//
// Finalize a previously requested release and receive the refund.
// Reverts before the unlock block or if no release is pending.
type IDiesisOperatorBondFinalizeReleaseParams struct {
	MarketId [32]byte
}

// IDiesisOperatorBondGetBondParams holds the arguments of getBond(bytes32).
//
// Read the public bond record for `marketId`.
type IDiesisOperatorBondGetBondParams struct {
	MarketId [32]byte
}

// IDiesisOperatorBondPostBondParams holds the arguments of postBond(bytes32).
//
// Post the operator bond for `marketId` with `msg.value` DS.
// `msg.value` must equal exactly 50,000 DS. Reverts if a bond already exists for `marketId`.
type IDiesisOperatorBondPostBondParams struct {
	MarketId [32]byte
}

// IDiesisOperatorBondRequestReleaseParams holds the arguments of requestRelease(bytes32).
//
// Request voluntary release of the bond.
// Subject to a 30-day timelock. Pending claims against the backstop must be resolved before the operator can finalize.
type IDiesisOperatorBondRequestReleaseParams struct {
	MarketId [32]byte
}

// IDiesisOperatorBondBondPostedEvent holds the fields of the BondPosted(address,bytes32,uint256) event.
type IDiesisOperatorBondBondPostedEvent struct {
	Operator common.Address
	MarketId [32]byte
	BondDs   *big.Int
}

// IDiesisOperatorBondBondSlashedEvent holds the fields of the BondSlashed(bytes32,uint256) event.
type IDiesisOperatorBondBondSlashedEvent struct {
	MarketId [32]byte
	AmountDs *big.Int
}

// IDiesisOperatorBondReleaseFinalizedEvent holds the fields of the ReleaseFinalized(bytes32,uint256) event.
type IDiesisOperatorBondReleaseFinalizedEvent struct {
	MarketId   [32]byte
	RefundedDs *big.Int
}

// IDiesisOperatorBondReleaseRequestedEvent holds the fields of the ReleaseRequested(bytes32,uint64) event.
type IDiesisOperatorBondReleaseRequestedEvent struct {
	MarketId    [32]byte
	UnlockBlock uint64
}

// IDiesisOperatorBondBinding provides typed calls, transactions, logs, and offline ABI encoding.
type IDiesisOperatorBondBinding struct {
	abi     abi.ABI
	bound   *bind.BoundContract
	backend bind.ContractBackend
	address common.Address
}

// NewIDiesisOperatorBondBinding parses the ABI and binds an optional backend. Pass nil for offline encoding and decoding.
func NewIDiesisOperatorBondBinding(address common.Address, backend bind.ContractBackend) (*IDiesisOperatorBondBinding, error) {
	parsed, err := abi.JSON(strings.NewReader(IDiesisOperatorBondABI))
	if err != nil {
		return nil, err
	}
	var bound *bind.BoundContract
	if backend != nil {
		bound = bind.NewBoundContract(address, parsed, backend, backend, backend)
	}
	return &IDiesisOperatorBondBinding{abi: parsed, bound: bound, backend: backend, address: address}, nil
}

// ABI returns the parsed contract ABI.
func (c *IDiesisOperatorBondBinding) ABI() abi.ABI { return c.abi }

func (c *IDiesisOperatorBondBinding) method(signature string) (abi.Method, error) {
	for _, method := range c.abi.Methods {
		if method.Sig == signature {
			return method, nil
		}
	}
	return abi.Method{}, fmt.Errorf("unknown method %s", signature)
}

func (c *IDiesisOperatorBondBinding) event(signature string) (abi.Event, error) {
	for _, event := range c.abi.Events {
		if event.Sig == signature {
			return event, nil
		}
	}
	return abi.Event{}, fmt.Errorf("unknown event %s", signature)
}

func (c *IDiesisOperatorBondBinding) customError(signature string) (abi.Error, error) {
	for _, definition := range c.abi.Errors {
		if definition.Sig == signature {
			return definition, nil
		}
	}
	return abi.Error{}, fmt.Errorf("unknown error %s", signature)
}

// EncodeConstructor encodes the constructor arguments without bytecode.
func (c *IDiesisOperatorBondBinding) EncodeConstructor() ([]byte, error) {
	return c.abi.Pack("")
}

// DeployIDiesisOperatorBondBinding deploys caller-supplied bytecode with typed constructor arguments.
func DeployIDiesisOperatorBondBinding(opts *bind.TransactOpts, backend bind.ContractBackend, bytecode []byte) (common.Address, *types.Transaction, *IDiesisOperatorBondBinding, error) {
	if opts == nil || backend == nil {
		return common.Address{}, nil, nil, fmt.Errorf("transaction options and backend are required")
	}
	if len(bytecode) == 0 {
		return common.Address{}, nil, nil, fmt.Errorf("deployment bytecode is empty")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return common.Address{}, nil, nil, fmt.Errorf("constructor is not payable")
	}
	parsed, err := abi.JSON(strings.NewReader(IDiesisOperatorBondABI))
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	address, tx, _, err := bind.DeployContract(opts, parsed, bytecode, backend)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	binding, err := NewIDiesisOperatorBondBinding(address, backend)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	return address, tx, binding, nil
}

// EncodeFinalizeRelease encodes calldata for "finalizeRelease(bytes32)".
func (c *IDiesisOperatorBondBinding) EncodeFinalizeRelease(params IDiesisOperatorBondFinalizeReleaseParams) ([]byte, error) {
	method, err := c.method("finalizeRelease(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.MarketId)
}

// DecodeFinalizeReleaseResult validates the empty return data of "finalizeRelease(bytes32)".
func (c *IDiesisOperatorBondBinding) DecodeFinalizeReleaseResult(data []byte) error {
	if len(data) != 0 {
		return fmt.Errorf("unexpected return data for %s", "finalizeRelease(bytes32)")
	}
	return nil
}

// FinalizeRelease submits "finalizeRelease(bytes32)"; opts supplies signer, gas, and optional value.
func (c *IDiesisOperatorBondBinding) FinalizeRelease(opts *bind.TransactOpts, params IDiesisOperatorBondFinalizeReleaseParams) (*types.Transaction, error) {
	if c.bound == nil {
		return nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	if opts == nil {
		return nil, fmt.Errorf("transaction options are required")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return nil, fmt.Errorf("%s is not payable", "finalizeRelease(bytes32)")
	}
	method, err := c.method("finalizeRelease(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.bound.Transact(opts, method.Name, params.MarketId)
}

// EncodeGetBond encodes calldata for "getBond(bytes32)".
func (c *IDiesisOperatorBondBinding) EncodeGetBond(params IDiesisOperatorBondGetBondParams) ([]byte, error) {
	method, err := c.method("getBond(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.MarketId)
}

// IDiesisOperatorBondGetBondResult holds the outputs of "getBond(bytes32)".
type IDiesisOperatorBondGetBondResult struct {
	BondInfo IDiesisOperatorBondBondInfo
}

// DecodeGetBondResult decodes the return data of "getBond(bytes32)".
func (c *IDiesisOperatorBondBinding) DecodeGetBondResult(data []byte) (out IDiesisOperatorBondGetBondResult, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI result: %v", failure)
		}
	}()
	method, err := c.method("getBond(bytes32)")
	if err != nil {
		return out, err
	}
	values, err := method.Outputs.Unpack(data)
	if err != nil {
		return out, err
	}
	if len(values) != 1 {
		return out, fmt.Errorf("result value count mismatch")
	}
	out.BondInfo = *abi.ConvertType(values[0], new(IDiesisOperatorBondBondInfo)).(*IDiesisOperatorBondBondInfo)
	return out, nil
}

// GetBond calls "getBond(bytes32)" on the bound backend.
func (c *IDiesisOperatorBondBinding) GetBond(opts *bind.CallOpts, params IDiesisOperatorBondGetBondParams) (IDiesisOperatorBondGetBondResult, error) {
	var zero IDiesisOperatorBondGetBondResult
	if c.bound == nil {
		return zero, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	input, err := c.EncodeGetBond(params)
	if err != nil {
		return zero, err
	}
	output, err := c.bound.CallRaw(opts, input)
	if err != nil {
		return zero, err
	}
	return c.DecodeGetBondResult(output)
}

// EncodePostBond encodes calldata for "postBond(bytes32)".
func (c *IDiesisOperatorBondBinding) EncodePostBond(params IDiesisOperatorBondPostBondParams) ([]byte, error) {
	method, err := c.method("postBond(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.MarketId)
}

// DecodePostBondResult validates the empty return data of "postBond(bytes32)".
func (c *IDiesisOperatorBondBinding) DecodePostBondResult(data []byte) error {
	if len(data) != 0 {
		return fmt.Errorf("unexpected return data for %s", "postBond(bytes32)")
	}
	return nil
}

// PostBond submits "postBond(bytes32)"; opts supplies signer, gas, and optional value.
func (c *IDiesisOperatorBondBinding) PostBond(opts *bind.TransactOpts, params IDiesisOperatorBondPostBondParams) (*types.Transaction, error) {
	if c.bound == nil {
		return nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	if opts == nil {
		return nil, fmt.Errorf("transaction options are required")
	}
	method, err := c.method("postBond(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.bound.Transact(opts, method.Name, params.MarketId)
}

// EncodeRequestRelease encodes calldata for "requestRelease(bytes32)".
func (c *IDiesisOperatorBondBinding) EncodeRequestRelease(params IDiesisOperatorBondRequestReleaseParams) ([]byte, error) {
	method, err := c.method("requestRelease(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.abi.Pack(method.Name, params.MarketId)
}

// DecodeRequestReleaseResult validates the empty return data of "requestRelease(bytes32)".
func (c *IDiesisOperatorBondBinding) DecodeRequestReleaseResult(data []byte) error {
	if len(data) != 0 {
		return fmt.Errorf("unexpected return data for %s", "requestRelease(bytes32)")
	}
	return nil
}

// RequestRelease submits "requestRelease(bytes32)"; opts supplies signer, gas, and optional value.
func (c *IDiesisOperatorBondBinding) RequestRelease(opts *bind.TransactOpts, params IDiesisOperatorBondRequestReleaseParams) (*types.Transaction, error) {
	if c.bound == nil {
		return nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	if opts == nil {
		return nil, fmt.Errorf("transaction options are required")
	}
	if opts.Value != nil && opts.Value.Sign() != 0 {
		return nil, fmt.Errorf("%s is not payable", "requestRelease(bytes32)")
	}
	method, err := c.method("requestRelease(bytes32)")
	if err != nil {
		return nil, err
	}
	return c.bound.Transact(opts, method.Name, params.MarketId)
}

// DecodeBondPostedEvent decodes a "BondPosted(address,bytes32,uint256)" log.
func (c *IDiesisOperatorBondBinding) DecodeBondPostedEvent(log types.Log) (out IDiesisOperatorBondBondPostedEvent, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI event: %v", failure)
		}
	}()
	definition, err := c.event("BondPosted(address,bytes32,uint256)")
	if err != nil {
		return out, err
	}
	if len(log.Topics) == 0 || log.Topics[0] != definition.ID {
		return out, fmt.Errorf("event signature mismatch for %s", "BondPosted(address,bytes32,uint256)")
	}
	if len(log.Topics) != 3 {
		return out, fmt.Errorf("event topic count mismatch for %s", "BondPosted(address,bytes32,uint256)")
	}
	if len(definition.Inputs.NonIndexed()) > 0 {
		values, err := definition.Inputs.NonIndexed().Unpack(log.Data)
		if err != nil {
			return out, err
		}
		if len(values) != 1 {
			return out, fmt.Errorf("event value count mismatch")
		}
		out.BondDs = *abi.ConvertType(values[0], new(*big.Int)).(**big.Int)
	} else if len(log.Data) != 0 {
		return out, fmt.Errorf("unexpected event data")
	}
	var indexed abi.Arguments
	var indexedTopics []common.Hash
	indexed = append(indexed, definition.Inputs[0])
	indexedTopics = append(indexedTopics, log.Topics[1])
	indexed = append(indexed, definition.Inputs[1])
	indexedTopics = append(indexedTopics, log.Topics[2])
	if err := abi.ParseTopics(&out, indexed, indexedTopics); err != nil {
		return out, err
	}
	return out, nil
}

// FilterBondPosted retrieves and decodes "BondPosted(address,bytes32,uint256)" logs. Indexed filters follow ABI order.
func (c *IDiesisOperatorBondBinding) FilterBondPosted(ctx context.Context, from, to *big.Int, indexed ...[]any) ([]IDiesisOperatorBondBondPostedEvent, error) {
	if c.backend == nil {
		return nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	definition, err := c.event("BondPosted(address,bytes32,uint256)")
	if err != nil {
		return nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, fmt.Errorf("too many indexed filters for %s", "BondPosted(address,bytes32,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, err
	}
	logs, err := c.backend.FilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics, FromBlock: from, ToBlock: to})
	if err != nil {
		return nil, err
	}
	out := make([]IDiesisOperatorBondBondPostedEvent, 0, len(logs))
	for _, log := range logs {
		decoded, err := c.DecodeBondPostedEvent(log)
		if err != nil {
			return nil, err
		}
		out = append(out, decoded)
	}
	return out, nil
}

// WatchBondPosted subscribes to new "BondPosted(address,bytes32,uint256)" logs and decodes them. Call Unsubscribe on the returned subscription when done.
func (c *IDiesisOperatorBondBinding) WatchBondPosted(ctx context.Context, indexed ...[]any) (<-chan IDiesisOperatorBondBondPostedEvent, event.Subscription, error) {
	if c.backend == nil {
		return nil, nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	definition, err := c.event("BondPosted(address,bytes32,uint256)")
	if err != nil {
		return nil, nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, nil, fmt.Errorf("too many indexed filters for %s", "BondPosted(address,bytes32,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, nil, err
	}
	logs := make(chan types.Log)
	upstream, err := c.backend.SubscribeFilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics}, logs)
	if err != nil {
		return nil, nil, err
	}
	events := make(chan IDiesisOperatorBondBondPostedEvent)
	subscription := event.NewSubscription(func(quit <-chan struct{}) error {
		defer upstream.Unsubscribe()
		defer close(events)
		for {
			select {
			case <-quit:
				return nil
			case <-ctx.Done():
				return ctx.Err()
			case err, ok := <-upstream.Err():
				if !ok {
					return nil
				}
				return err
			case log, ok := <-logs:
				if !ok {
					return nil
				}
				decoded, err := c.DecodeBondPostedEvent(log)
				if err != nil {
					return err
				}
				select {
				case events <- decoded:
				case <-quit:
					return nil
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})
	return events, subscription, nil
}

// DecodeBondSlashedEvent decodes a "BondSlashed(bytes32,uint256)" log.
func (c *IDiesisOperatorBondBinding) DecodeBondSlashedEvent(log types.Log) (out IDiesisOperatorBondBondSlashedEvent, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI event: %v", failure)
		}
	}()
	definition, err := c.event("BondSlashed(bytes32,uint256)")
	if err != nil {
		return out, err
	}
	if len(log.Topics) == 0 || log.Topics[0] != definition.ID {
		return out, fmt.Errorf("event signature mismatch for %s", "BondSlashed(bytes32,uint256)")
	}
	if len(log.Topics) != 2 {
		return out, fmt.Errorf("event topic count mismatch for %s", "BondSlashed(bytes32,uint256)")
	}
	if len(definition.Inputs.NonIndexed()) > 0 {
		values, err := definition.Inputs.NonIndexed().Unpack(log.Data)
		if err != nil {
			return out, err
		}
		if len(values) != 1 {
			return out, fmt.Errorf("event value count mismatch")
		}
		out.AmountDs = *abi.ConvertType(values[0], new(*big.Int)).(**big.Int)
	} else if len(log.Data) != 0 {
		return out, fmt.Errorf("unexpected event data")
	}
	var indexed abi.Arguments
	var indexedTopics []common.Hash
	indexed = append(indexed, definition.Inputs[0])
	indexedTopics = append(indexedTopics, log.Topics[1])
	if err := abi.ParseTopics(&out, indexed, indexedTopics); err != nil {
		return out, err
	}
	return out, nil
}

// FilterBondSlashed retrieves and decodes "BondSlashed(bytes32,uint256)" logs. Indexed filters follow ABI order.
func (c *IDiesisOperatorBondBinding) FilterBondSlashed(ctx context.Context, from, to *big.Int, indexed ...[]any) ([]IDiesisOperatorBondBondSlashedEvent, error) {
	if c.backend == nil {
		return nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	definition, err := c.event("BondSlashed(bytes32,uint256)")
	if err != nil {
		return nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, fmt.Errorf("too many indexed filters for %s", "BondSlashed(bytes32,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, err
	}
	logs, err := c.backend.FilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics, FromBlock: from, ToBlock: to})
	if err != nil {
		return nil, err
	}
	out := make([]IDiesisOperatorBondBondSlashedEvent, 0, len(logs))
	for _, log := range logs {
		decoded, err := c.DecodeBondSlashedEvent(log)
		if err != nil {
			return nil, err
		}
		out = append(out, decoded)
	}
	return out, nil
}

// WatchBondSlashed subscribes to new "BondSlashed(bytes32,uint256)" logs and decodes them. Call Unsubscribe on the returned subscription when done.
func (c *IDiesisOperatorBondBinding) WatchBondSlashed(ctx context.Context, indexed ...[]any) (<-chan IDiesisOperatorBondBondSlashedEvent, event.Subscription, error) {
	if c.backend == nil {
		return nil, nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	definition, err := c.event("BondSlashed(bytes32,uint256)")
	if err != nil {
		return nil, nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, nil, fmt.Errorf("too many indexed filters for %s", "BondSlashed(bytes32,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, nil, err
	}
	logs := make(chan types.Log)
	upstream, err := c.backend.SubscribeFilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics}, logs)
	if err != nil {
		return nil, nil, err
	}
	events := make(chan IDiesisOperatorBondBondSlashedEvent)
	subscription := event.NewSubscription(func(quit <-chan struct{}) error {
		defer upstream.Unsubscribe()
		defer close(events)
		for {
			select {
			case <-quit:
				return nil
			case <-ctx.Done():
				return ctx.Err()
			case err, ok := <-upstream.Err():
				if !ok {
					return nil
				}
				return err
			case log, ok := <-logs:
				if !ok {
					return nil
				}
				decoded, err := c.DecodeBondSlashedEvent(log)
				if err != nil {
					return err
				}
				select {
				case events <- decoded:
				case <-quit:
					return nil
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})
	return events, subscription, nil
}

// DecodeReleaseFinalizedEvent decodes a "ReleaseFinalized(bytes32,uint256)" log.
func (c *IDiesisOperatorBondBinding) DecodeReleaseFinalizedEvent(log types.Log) (out IDiesisOperatorBondReleaseFinalizedEvent, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI event: %v", failure)
		}
	}()
	definition, err := c.event("ReleaseFinalized(bytes32,uint256)")
	if err != nil {
		return out, err
	}
	if len(log.Topics) == 0 || log.Topics[0] != definition.ID {
		return out, fmt.Errorf("event signature mismatch for %s", "ReleaseFinalized(bytes32,uint256)")
	}
	if len(log.Topics) != 2 {
		return out, fmt.Errorf("event topic count mismatch for %s", "ReleaseFinalized(bytes32,uint256)")
	}
	if len(definition.Inputs.NonIndexed()) > 0 {
		values, err := definition.Inputs.NonIndexed().Unpack(log.Data)
		if err != nil {
			return out, err
		}
		if len(values) != 1 {
			return out, fmt.Errorf("event value count mismatch")
		}
		out.RefundedDs = *abi.ConvertType(values[0], new(*big.Int)).(**big.Int)
	} else if len(log.Data) != 0 {
		return out, fmt.Errorf("unexpected event data")
	}
	var indexed abi.Arguments
	var indexedTopics []common.Hash
	indexed = append(indexed, definition.Inputs[0])
	indexedTopics = append(indexedTopics, log.Topics[1])
	if err := abi.ParseTopics(&out, indexed, indexedTopics); err != nil {
		return out, err
	}
	return out, nil
}

// FilterReleaseFinalized retrieves and decodes "ReleaseFinalized(bytes32,uint256)" logs. Indexed filters follow ABI order.
func (c *IDiesisOperatorBondBinding) FilterReleaseFinalized(ctx context.Context, from, to *big.Int, indexed ...[]any) ([]IDiesisOperatorBondReleaseFinalizedEvent, error) {
	if c.backend == nil {
		return nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	definition, err := c.event("ReleaseFinalized(bytes32,uint256)")
	if err != nil {
		return nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, fmt.Errorf("too many indexed filters for %s", "ReleaseFinalized(bytes32,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, err
	}
	logs, err := c.backend.FilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics, FromBlock: from, ToBlock: to})
	if err != nil {
		return nil, err
	}
	out := make([]IDiesisOperatorBondReleaseFinalizedEvent, 0, len(logs))
	for _, log := range logs {
		decoded, err := c.DecodeReleaseFinalizedEvent(log)
		if err != nil {
			return nil, err
		}
		out = append(out, decoded)
	}
	return out, nil
}

// WatchReleaseFinalized subscribes to new "ReleaseFinalized(bytes32,uint256)" logs and decodes them. Call Unsubscribe on the returned subscription when done.
func (c *IDiesisOperatorBondBinding) WatchReleaseFinalized(ctx context.Context, indexed ...[]any) (<-chan IDiesisOperatorBondReleaseFinalizedEvent, event.Subscription, error) {
	if c.backend == nil {
		return nil, nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	definition, err := c.event("ReleaseFinalized(bytes32,uint256)")
	if err != nil {
		return nil, nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, nil, fmt.Errorf("too many indexed filters for %s", "ReleaseFinalized(bytes32,uint256)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, nil, err
	}
	logs := make(chan types.Log)
	upstream, err := c.backend.SubscribeFilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics}, logs)
	if err != nil {
		return nil, nil, err
	}
	events := make(chan IDiesisOperatorBondReleaseFinalizedEvent)
	subscription := event.NewSubscription(func(quit <-chan struct{}) error {
		defer upstream.Unsubscribe()
		defer close(events)
		for {
			select {
			case <-quit:
				return nil
			case <-ctx.Done():
				return ctx.Err()
			case err, ok := <-upstream.Err():
				if !ok {
					return nil
				}
				return err
			case log, ok := <-logs:
				if !ok {
					return nil
				}
				decoded, err := c.DecodeReleaseFinalizedEvent(log)
				if err != nil {
					return err
				}
				select {
				case events <- decoded:
				case <-quit:
					return nil
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})
	return events, subscription, nil
}

// DecodeReleaseRequestedEvent decodes a "ReleaseRequested(bytes32,uint64)" log.
func (c *IDiesisOperatorBondBinding) DecodeReleaseRequestedEvent(log types.Log) (out IDiesisOperatorBondReleaseRequestedEvent, err error) {
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("invalid ABI event: %v", failure)
		}
	}()
	definition, err := c.event("ReleaseRequested(bytes32,uint64)")
	if err != nil {
		return out, err
	}
	if len(log.Topics) == 0 || log.Topics[0] != definition.ID {
		return out, fmt.Errorf("event signature mismatch for %s", "ReleaseRequested(bytes32,uint64)")
	}
	if len(log.Topics) != 2 {
		return out, fmt.Errorf("event topic count mismatch for %s", "ReleaseRequested(bytes32,uint64)")
	}
	if len(definition.Inputs.NonIndexed()) > 0 {
		values, err := definition.Inputs.NonIndexed().Unpack(log.Data)
		if err != nil {
			return out, err
		}
		if len(values) != 1 {
			return out, fmt.Errorf("event value count mismatch")
		}
		out.UnlockBlock = *abi.ConvertType(values[0], new(uint64)).(*uint64)
	} else if len(log.Data) != 0 {
		return out, fmt.Errorf("unexpected event data")
	}
	var indexed abi.Arguments
	var indexedTopics []common.Hash
	indexed = append(indexed, definition.Inputs[0])
	indexedTopics = append(indexedTopics, log.Topics[1])
	if err := abi.ParseTopics(&out, indexed, indexedTopics); err != nil {
		return out, err
	}
	return out, nil
}

// FilterReleaseRequested retrieves and decodes "ReleaseRequested(bytes32,uint64)" logs. Indexed filters follow ABI order.
func (c *IDiesisOperatorBondBinding) FilterReleaseRequested(ctx context.Context, from, to *big.Int, indexed ...[]any) ([]IDiesisOperatorBondReleaseRequestedEvent, error) {
	if c.backend == nil {
		return nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	definition, err := c.event("ReleaseRequested(bytes32,uint64)")
	if err != nil {
		return nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, fmt.Errorf("too many indexed filters for %s", "ReleaseRequested(bytes32,uint64)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, err
	}
	logs, err := c.backend.FilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics, FromBlock: from, ToBlock: to})
	if err != nil {
		return nil, err
	}
	out := make([]IDiesisOperatorBondReleaseRequestedEvent, 0, len(logs))
	for _, log := range logs {
		decoded, err := c.DecodeReleaseRequestedEvent(log)
		if err != nil {
			return nil, err
		}
		out = append(out, decoded)
	}
	return out, nil
}

// WatchReleaseRequested subscribes to new "ReleaseRequested(bytes32,uint64)" logs and decodes them. Call Unsubscribe on the returned subscription when done.
func (c *IDiesisOperatorBondBinding) WatchReleaseRequested(ctx context.Context, indexed ...[]any) (<-chan IDiesisOperatorBondReleaseRequestedEvent, event.Subscription, error) {
	if c.backend == nil {
		return nil, nil, fmt.Errorf("IDiesisOperatorBondBinding has no backend")
	}
	definition, err := c.event("ReleaseRequested(bytes32,uint64)")
	if err != nil {
		return nil, nil, err
	}
	count := 0
	for _, arg := range definition.Inputs {
		if arg.Indexed {
			count++
		}
	}
	if len(indexed) > count {
		return nil, nil, fmt.Errorf("too many indexed filters for %s", "ReleaseRequested(bytes32,uint64)")
	}
	queries := indexed
	queries = append([][]any{{definition.ID}}, queries...)
	topics, err := abi.MakeTopics(queries...)
	if err != nil {
		return nil, nil, err
	}
	logs := make(chan types.Log)
	upstream, err := c.backend.SubscribeFilterLogs(ctx, ethereum.FilterQuery{Addresses: []common.Address{c.address}, Topics: topics}, logs)
	if err != nil {
		return nil, nil, err
	}
	events := make(chan IDiesisOperatorBondReleaseRequestedEvent)
	subscription := event.NewSubscription(func(quit <-chan struct{}) error {
		defer upstream.Unsubscribe()
		defer close(events)
		for {
			select {
			case <-quit:
				return nil
			case <-ctx.Done():
				return ctx.Err()
			case err, ok := <-upstream.Err():
				if !ok {
					return nil
				}
				return err
			case log, ok := <-logs:
				if !ok {
					return nil
				}
				decoded, err := c.DecodeReleaseRequestedEvent(log)
				if err != nil {
					return err
				}
				select {
				case events <- decoded:
				case <-quit:
					return nil
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})
	return events, subscription, nil
}

// DecodeError identifies and decodes a declared custom error.
func (c *IDiesisOperatorBondBinding) DecodeError(raw []byte) (any, error) {
	if len(raw) < 4 {
		return nil, fmt.Errorf("revert payload is shorter than a selector")
	}
	return nil, fmt.Errorf("unknown custom error selector %x", raw[:4])
}
