#!/usr/bin/env python3
"""Regenerate the Go bindings, addresses, chains, and contract table.

Default mode rewrites every generated file and re-vendors canonical.json from
../diesis-js/canonical.json. `--check` writes nothing and exits non-zero if
any generated file or the vendored canonical.json differs from what this
script would produce.

Inputs:
  DIESIS_CONTRACTS_DIR  contracts checkout (default ../../diesis-core/diesis/contracts)
  ABI_TYPEGEN           abi-typegen 0.8.0 or newer (default <contracts>/node_modules/.bin/abi-typegen)
  GOFMT                 gofmt binary (default gofmt on PATH)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS_DIR = Path(
    os.environ.get("DIESIS_CONTRACTS_DIR") or ROOT.parent.parent / "diesis-core" / "diesis" / "contracts"
).resolve()
TYPEGEN = Path(
    os.environ.get("ABI_TYPEGEN")
    or CONTRACTS_DIR / "node_modules" / ".bin" / "abi-typegen"
).resolve()
GOFMT = os.environ.get("GOFMT", "gofmt")
SDK_CANONICAL = ROOT.parent / "diesis-js" / "canonical.json"
CANONICAL = ROOT / "canonical.json"
BINDINGS_DIR = ROOT / "contracts"

HEADER = "// Code generated by scripts/generate.py. DO NOT EDIT.\n\n"

# Contracts that third-party integrations call. This is the same list, in the
# same order, as diesis-js/scripts/generate-contract-bindings.mjs. The third
# field names the canonical.json address; None means no fixed address, so the
# contract gets bindings but no contract table entry.
PUBLIC_CONTRACTS: list[tuple[str, str, str | None]] = [
    ("markets", "IDiesisMarkets", "DIESIS_MARKETS"),
    ("spotBook", "IDiesisSpotBook", "DIESIS_SPOT_BOOK"),
    ("perpsBook", "IDiesisPerpsBook", "DIESIS_PERPS_BOOK"),
    ("margin", "IDiesisMargin", "DIESIS_MARGIN"),
    ("settlement", "IDiesisSettlement", "DIESIS_SETTLEMENT"),
    ("settlementRouter", "DiesisSettlementRouter", "DIESIS_SETTLEMENT_ROUTER"),
    ("conductors", "IDiesisConductors", "DIESIS_CONDUCTORS"),
    ("erc20Factory", "IDiesisErc20Factory", "DIESIS_ERC20_FACTORY"),
    ("perpDeploy", "IDiesisPerpDeploy", "DIESIS_PERP_DEPLOY"),
    ("operatorBond", "IDiesisOperatorBond", "DIESIS_OPERATOR_BOND"),
    ("bundleEscrow", "IDiesisBundleEscrow", "DIESIS_BUNDLE_ESCROW"),
    ("staking", "DiesisStaking", "DIESIS_STAKING"),
    ("position", "IDiesisPosition", "DIESIS_POSITION"),
    ("validatorShare", "IValidatorShare", None),
    ("liquidStakedDS", "ILiquidStakedDS", "LIQUID_STAKED_DS"),
    ("wrappedDS", "IWrappedDS", "WRAPPED_DS"),
    ("patron", "DiesisPatron", "DIESIS_PATRON"),
    ("config", "DiesisConfig", "DIESIS_CONFIG"),
    ("coreVault", "IDiesisCoreVault", "DIESIS_CORE_VAULT"),
    ("issuanceAuction", "IDiesisIssuanceAuction", "DIESIS_ISSUANCE_AUCTION"),
    ("buybackBurn", "IDiesisBuybackBurn", "DIESIS_BUYBACK_BURN"),
    ("shieldedPool", "DiesisShieldedPool", "SHIELDED_POOL"),
    ("privacyPools", "DiesisPrivacyPools", "PRIVACY_POOLS"),
    ("nameRegistry", "IDiesisNameRegistry", "DIESIS_NAME_REGISTRY"),
    ("baseRegistrar", "DiesisBaseRegistrar", "DIESIS_BASE_REGISTRAR"),
    ("publicResolver", "DiesisPublicResolver", "DIESIS_PUBLIC_RESOLVER"),
    ("reverseRegistrar", "IDiesisReverseRegistrar", "DIESIS_REVERSE_REGISTRAR"),
    ("nameVerifier", "IDiesisNameVerifier", "DIESIS_NAME_VERIFIER"),
    ("namePolicy", "IDiesisNamePolicy", "DIESIS_NAME_POLICY"),
]

# Words kept upper case in Go identifiers.
INITIALISMS = {"DS", "USD", "VRF", "ERC20", "ML", "DSA"}


def go_ident(screaming: str) -> str:
    """DIESIS_SPOT_BOOK -> DiesisSpotBook, WRAPPED_DS -> WrappedDS."""
    parts = []
    for word in screaming.split("_"):
        parts.append(word if word in INITIALISMS else word[0] + word[1:].lower())
    return "".join(parts)


def go_field(key: str) -> str:
    """spotBook -> SpotBook, erc20Factory -> ERC20Factory."""
    words = re.findall(r"[a-z0-9]+|[A-Z]+[a-z0-9]*", key)
    return "".join(
        w.upper() if w.upper() in INITIALISMS else w[0].upper() + w[1:] for w in words
    )


def gofmt(source: str) -> str:
    result = subprocess.run(
        [GOFMT], input=source, capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        sys.exit(f"gofmt failed:\n{result.stderr}")
    return result.stdout


MIN_TYPEGEN = (0, 8, 0)
GO_PACKAGE = "contracts"


def check_typegen_version() -> None:
    result = subprocess.run(
        [str(TYPEGEN), "--version"], capture_output=True, text=True, check=True
    )
    match = re.search(r"(\d+)\.(\d+)\.(\d+)", result.stdout)
    if not match:
        sys.exit(f"cannot read abi-typegen version from {result.stdout!r}")
    found = tuple(int(part) for part in match.groups())
    if found < MIN_TYPEGEN:
        want = ".".join(map(str, MIN_TYPEGEN))
        sys.exit(f"abi-typegen {match.group(0)} is too old; need {want} or newer")


def run_typegen() -> dict[str, str]:
    if not TYPEGEN.exists():
        sys.exit(f"abi-typegen not found at {TYPEGEN}; set ABI_TYPEGEN")
    check_typegen_version()
    artifacts = CONTRACTS_DIR / "out"
    if not artifacts.is_dir():
        sys.exit(f"compiled artifacts not found at {artifacts}; build the contracts")
    names = [contract for _, contract, _ in PUBLIC_CONTRACTS]
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            [
                str(TYPEGEN),
                "generate",
                "--artifacts",
                str(artifacts),
                "--out",
                tmp,
                "--target",
                "go",
                "--package",
                GO_PACKAGE,
                "--contracts",
                ",".join(names),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
        )
        produced = sorted(p.name for p in Path(tmp).glob("*.go"))
        expected = sorted(f"{n}.go" for n in names)
        if produced != expected:
            sys.exit(f"abi-typegen produced {produced}, expected {expected}")
        # abi-typegen 0.5.0 output is gofmt-clean except where NatSpec uses
        # ``double backticks``, which gofmt rewrites in doc comments.
        return {
            f"contracts/{name}": gofmt((Path(tmp) / name).read_text())
            for name in produced
        }


def render_addresses(canonical: dict) -> str:
    addresses = canonical["addresses"]
    lines = [
        HEADER,
        "package diesis\n\n",
        'import "github.com/ethereum/go-ethereum/common"\n\n',
        "// System contract and precompile addresses from canonical.json.\n",
        "var (\n",
    ]
    for name, value in addresses.items():
        lines.append(f"\t// {go_ident(name)} is {name}.\n")
        lines.append(f'\t{go_ident(name)} = common.HexToAddress("{value}")\n')
    lines.append(")\n\n")
    lines.append(
        "// Addresses maps each canonical.json address name, such as\n"
        '// "DIESIS_STAKING", to its address.\n'
        "var Addresses = map[string]common.Address{\n"
    )
    for name in addresses:
        lines.append(f'\t"{name}": {go_ident(name)},\n')
    lines.append("}\n")
    return gofmt("".join(lines))


def render_chains(canonical: dict) -> str:
    chains = canonical["chains"]
    lines = [
        HEADER,
        "package diesis\n\n",
        "// SchemaVersion is the canonical.json schema version these values came from.\n",
        f"const SchemaVersion = {int(canonical['schemaVersion'])}\n\n",
        "// Chain IDs.\n",
        "const (\n",
    ]
    for key, chain in chains.items():
        lines.append(f"\t{key.capitalize()}ChainID uint64 = {int(chain['id'])}\n")
    lines.append(")\n\n")
    for key, chain in chains.items():
        currency = chain["nativeCurrency"]
        ident = key.capitalize()
        lines.append(f"// {ident} is the {chain['name']} chain ({int(chain['id'])}).\n")
        lines.append(f"var {ident} = Chain{{\n")
        lines.append(f"\tID: {ident}ChainID,\n")
        lines.append(f"\tName: {json.dumps(chain['name'])},\n")
        lines.append(
            "\tNativeCurrency: NativeCurrency{"
            f"Name: {json.dumps(currency['name'])}, "
            f"Symbol: {json.dumps(currency['symbol'])}, "
            f"Decimals: {int(currency['decimals'])}}},\n"
        )
        lines.append(f"\tRPCURL: {json.dumps(chain['rpcUrl'])},\n")
        lines.append(f"\tExplorerURL: {json.dumps(chain['explorerUrl'])},\n")
        lines.append(f"\tTestnet: {'true' if chain['testnet'] else 'false'},\n")
        lines.append("}\n\n")
    lines.append("// Chains lists every Diesis chain, mainnet first.\n")
    lines.append(
        "var Chains = []Chain{"
        + ", ".join(key.capitalize() for key in chains)
        + "}\n"
    )
    return gofmt("".join(lines))


def render_contract_table(canonical: dict) -> str:
    addresses = canonical["addresses"]
    fixed = [(k, c, a) for k, c, a in PUBLIC_CONTRACTS if a is not None]
    for _, _, address in fixed:
        if address not in addresses:
            sys.exit(f"{address} is missing from canonical.json")
    lines = [
        HEADER,
        "package diesis\n\n",
        'import "github.com/0xDiesis/diesis-go/contracts"\n\n',
        "// ContractTable has one entry per public system contract with a fixed\n",
        "// address. Field names match the keys of diesisContracts in the\n",
        "// TypeScript SDK.\n",
        "type ContractTable struct {\n",
    ]
    for key, contract, _ in fixed:
        lines.append(f"\t{go_field(key)} Contract // {contract}\n")
    lines.append("}\n\n")
    lines.append(
        "// Contracts pairs each fixed-address public system contract with its\n"
        "// address and generated ABI.\n"
        "var Contracts = ContractTable{\n"
    )
    for key, contract, address in fixed:
        lines.append(
            f"\t{go_field(key)}: Contract{{Key: {json.dumps(key)}, "
            f"Name: {json.dumps(contract)}, Address: {go_ident(address)}, "
            f"ABI: contracts.{contract}ABI}},\n"
        )
    lines.append("}\n\n")
    lines.append(
        "// All returns every entry in the table, in the TypeScript SDK's order.\n"
        "func (t ContractTable) All() []Contract {\n"
        "\treturn []Contract{\n"
    )
    for key, _, _ in fixed:
        lines.append(f"\t\tt.{go_field(key)},\n")
    lines.append("\t}\n}\n\n")
    lines.append(
        "// ABIs maps every public contract name, including contracts without a\n"
        "// fixed address, to its generated ABI JSON.\n"
        "var ABIs = map[string]string{\n"
    )
    for _, contract, _ in PUBLIC_CONTRACTS:
        lines.append(f'\t"{contract}": contracts.{contract}ABI,\n')
    lines.append("}\n")
    return gofmt("".join(lines))


def expected_files() -> dict[str, str]:
    canonical_text = SDK_CANONICAL.read_text()
    canonical = json.loads(canonical_text)
    files = run_typegen()
    files["addresses.go"] = render_addresses(canonical)
    files["chains.go"] = render_chains(canonical)
    files["contract_table.go"] = render_contract_table(canonical)
    files["canonical.json"] = canonical_text
    return files


def stale_bindings(files: dict[str, str]) -> list[str]:
    if not BINDINGS_DIR.is_dir():
        return []
    return sorted(
        f"contracts/{p.name}"
        for p in BINDINGS_DIR.glob("*.go")
        if f"contracts/{p.name}" not in files
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if generated files are stale"
    )
    args = parser.parse_args()

    if not SDK_CANONICAL.exists():
        sys.exit(f"{SDK_CANONICAL} not found")
    files = expected_files()
    stale = stale_bindings(files)

    if args.check:
        problems = []
        for rel, content in sorted(files.items()):
            path = ROOT / rel
            if not path.exists():
                problems.append(f"missing: {rel}")
            elif path.read_text() != content:
                problems.append(f"out of date: {rel}")
        problems += [f"not generated: {rel}" for rel in stale]
        if problems:
            print("\n".join(problems), file=sys.stderr)
            print("run: python3 scripts/generate.py", file=sys.stderr)
            return 1
        print(f"up to date: {len(files)} files")
        return 0

    for rel in stale:
        (ROOT / rel).unlink()
    for rel, content in files.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
    print(f"generated {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
